OK-14094, OK-14067, OK-14253 Improve NFT UI
OneKeyHQ/app-monorepo pull request #1966
Opened 2022-11-11 11:52 UTC by franco-chan

2022-11-11 13:06 UTC, loatheb requested changes

2022-11-11 13:06 UTC, loatheb commented on yarn.lock
> +"@onekeyfe/hd-ble-sdk@npm:0.2.1":
怎么又给升级回去了

2022-11-11 13:18 UTC, franco-chan commented on yarn.lock
> +"@onekeyfe/hd-ble-sdk@npm:0.2.1":
已用主分支的 lock 文件覆盖

2022-11-11 13:19 UTC, loatheb approved these changes, later dismissed

2022-11-12 06:24 UTC, loatheb approved these changes

2022-11-12 08:07 UTC, sunnylqm approved these changes

2022-11-12 09:27 UTC, linleiqin approved these changes

2022-11-12 09:27 UTC, merged