fix: mas-build-version & mas onboarding miss
OneKeyHQ/app-monorepo pull request #2106
Opened 2022-11-30 06:33 UTC by ezailWang

2022-11-30 06:44 UTC, loatheb approved these changes

2022-11-30 06:45 UTC, originalix approved these changes, later dismissed

2022-11-30 06:45 UTC, loatheb requested changes

2022-11-30 06:45 UTC, loatheb commented on packages/kit/src/routes/Root/index.tsx
> +  // const boardingCompleted = useAppSelector((s) => s.status.boardingCompleted);
要不先只改版本呢，这个就下个版本单独改了

2022-11-30 06:47 UTC, ezailWang commented on packages/kit/src/routes/Root/index.tsx
> +  // const boardingCompleted = useAppSelector((s) => s.status.boardingCompleted);
那我分一个pr出来吧

2022-12-01 01:45 UTC, sunnylqm approved these changes, later dismissed

2022-12-01 01:59 UTC, qwang1113 approved these changes, later dismissed

2022-12-01 04:03 UTC, weatherstar approved these changes

2022-12-01 04:19 UTC, loatheb approved these changes

2022-12-01 04:20 UTC, linleiqin approved these changes

2022-12-01 04:45 UTC, merged