fix: select position in native stack OK-15289
OneKeyHQ/app-monorepo pull request #2188
Opened 2022-12-12 15:33 UTC by sunnylqm

2022-12-12 15:45 UTC, loatheb requested changes

2022-12-12 15:45 UTC, loatheb commented on packages/kit/src/views/Webview/index.tsx
> +    setTimeout(main);
不加延迟好像 ios 会卡住还是系统那个框不会弹出来的，我记得 @ByteZhang1024 最开始遇到过这个问题

2022-12-13 01:34 UTC, sunnylqm commented on packages/kit/src/views/Webview/index.tsx
> +    setTimeout(main);
我重写下吧

2022-12-13 02:11 UTC, sidmorizon approved these changes

2022-12-13 02:54 UTC, kwoktung approved these changes

2022-12-13 02:54 UTC, qwang1113 approved these changes

2022-12-13 03:06 UTC, revan-zhang approved these changes

2022-12-13 03:06 UTC, merged