feat: discover page i18n
OneKeyHQ/app-monorepo pull request #2354
Opened 2023-01-05 13:07 UTC by kwoktung

2023-01-05 14:15 UTC, sunnylqm approved these changes, later dismissed

2023-01-05 14:37 UTC, loatheb requested changes

2023-01-05 14:37 UTC, loatheb commented on packages/kit/src/utils/locale.ts
> +    'system': 'en',
lokalise 后台可以改生成的 symbol，不用客户端做映射，否则以后新增语言好多个地方的配置得改，我们就每个项目都统一一份语言 symbol 就行

2023-01-06 04:28 UTC, revan-zhang approved these changes

2023-01-06 04:36 UTC, linleiqin approved these changes

2023-01-06 04:52 UTC, ByteZhang1024 approved these changes

2023-01-06 05:16 UTC, merged