OK-14622: optimize ble
OneKeyHQ/app-monorepo pull request #2508
Opened 2023-02-07 02:05 UTC by ByteZhang1024

2023-02-07 02:20 UTC, originalix requested changes

2023-02-07 02:20 UTC, originalix commented on packages/app/package.json
> +    "@my01/react-native-ble-plx": "^2.1.0",
这个好像不是官方库

2023-02-07 03:40 UTC, originalix submitted a review, later dismissed

2023-02-07 05:56 UTC, sidmorizon submitted a review, later dismissed

2023-02-07 06:01 UTC, ByteZhang1024 commented on packages/app/package.json
> +    "@my01/react-native-ble-plx": "^2.1.0",
我看了代码修改，适配了最新的 Android 蓝牙库。不然这个事我们自己还要做一遍。

2023-02-07 07:00 UTC, originalix approved these changes, later dismissed

2023-02-07 07:00 UTC, linleiqin approved these changes, later dismissed

2023-02-07 07:01 UTC, loatheb commented on packages/app/package.json
> +    "@my01/react-native-ble-plx": "^2.1.0",
fork 一份过来呢？这样比较稳妥

2023-02-07 07:04 UTC, sunnylqm approved these changes, later dismissed

2023-02-07 07:30 UTC, sidmorizon submitted a review, later dismissed

2023-02-09 01:28 UTC, originalix approved these changes

2023-02-09 01:37 UTC, qwang1113 approved these changes

2023-02-09 01:43 UTC, loatheb approved these changes

2023-02-09 01:43 UTC, merged