fix: home tab switch
OneKeyHQ/app-monorepo pull request #2517
Opened 2023-02-08 09:56 UTC by sidmorizon

2023-02-08 09:58 UTC, sunnylqm approved these changes

2023-02-08 10:12 UTC, originalix approved these changes

2023-02-09 01:46 UTC, ByteZhang1024 approved these changes

2023-02-09 01:55 UTC, qwang1113 requested changes, later dismissed

2023-02-09 01:55 UTC, qwang1113 commented on packages/kit/src/views/Wallet/index.tsx
> +    backgroundApiProxy.dispatch(setHomeTabName(HomeTabOrder[0]));
这样改动在插件段可能会有问题, 比如插件端推送点击, 需要切换这个tab到历史记录那一栏

点击的方法是在background 里面, 
dispatch(setHomeTabName(HomeTabOrder[2]));
然后再打开UI, 这里执行又会被设置回来了

2023-02-09 06:14 UTC, sidmorizon commented on packages/kit/src/views/Wallet/index.tsx
> +    backgroundApiProxy.dispatch(setHomeTabName(HomeTabOrder[0]));
目前线上版本的插件已经不支持通过 redux 状态来保持 Tab 状态了，之前是可以的， @sunnylqm

2023-02-09 06:43 UTC, merged