fix: mas cert invaild
OneKeyHQ/app-monorepo pull request #2525
Opened 2023-02-09 11:36 UTC by ezailWang

2023-02-09 12:13 UTC, sunnylqm submitted a review, later dismissed

2023-02-10 04:50 UTC, sunnylqm approved these changes, later dismissed

2023-02-10 05:58 UTC, sidmorizon approved these changes, later dismissed

2023-02-10 06:21 UTC, loatheb requested changes

2023-02-10 06:21 UTC, loatheb commented on .github/workflows/release-desktop-mas.yml
> +          security import $MAC_INSTALL_P12_PATH -P "" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
密码去掉了？

2023-02-10 07:13 UTC, loatheb approved these changes

2023-02-10 07:36 UTC, qwang1113 approved these changes

2023-02-10 07:38 UTC, ByteZhang1024 approved these changes

2023-02-10 07:51 UTC, merged