fix: add error message to form item OK-14959
OneKeyHQ/app-monorepo pull request #2533
Opened 2023-02-10 10:57 UTC by ezailWang

2023-02-10 13:17 UTC, loatheb requested changes

2023-02-10 13:17 UTC, loatheb commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +  const timer = useRef<any>();
类型是 `ReturnType<typeof setTimeout>` 吗

2023-02-10 13:17 UTC, loatheb commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +      timer.current = setTimeout(async () => {
校验有延迟的话，底下的提交按钮是否会出现在这 100ms 能点击提交的情况

2023-02-10 13:17 UTC, loatheb commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +        setErrorMessage('');
这三个属性放到一个 state 是不是好一点，看这段逻辑基本都是一起更新的

2023-02-13 01:44 UTC, ezailWang commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +        setErrorMessage('');
这3个属性显示是互斥的

2023-02-13 01:46 UTC, ezailWang commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +      timer.current = setTimeout(async () => {
const submitDisabled =
    isLoading ||
    !formValues?.to ||
    !isValid ||
    formState.isValidating ||
    disableSubmitBtn ||
    errorMessage.length > 0;   
    按钮的enable，在校验之前isValid 是false的

2023-02-13 01:47 UTC, ezailWang commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +  const timer = useRef<any>();
这个改下类型

2023-02-13 01:48 UTC, loatheb commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +        setErrorMessage('');
放到一个对象里面是不是对更新周期或者代码执行有帮助的 `const buttonStatus = useState({successMessage: '', warningMessage: '', errorMessage})`

2023-02-13 02:03 UTC, ezailWang commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +        setErrorMessage('');
1

2023-02-13 02:26 UTC, sunnylqm commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +        setErrorMessage('');
用{ message: string, type: 'error' | 'warning' | 'success' } 就行了吧

2023-02-13 02:27 UTC, qwang1113 submitted a review, later dismissed

2023-02-13 03:00 UTC, loatheb commented on packages/kit/src/views/Send/modals/PreSendAddress.tsx
> +  const timer = useRef<NodeJS.Timeout>();
这是个平台相关的类型吧，咱们尽量还是不用这种形式最好还是用通用的严谨的类型推导 ReturnType 范型来处理..

2023-02-13 03:25 UTC, weatherstar approved these changes

2023-02-13 03:29 UTC, loatheb approved these changes

2023-02-13 03:32 UTC, qwang1113 approved these changes

2023-02-13 03:32 UTC, merged