feat: add shortcuts for explorer OK-16782
OneKeyHQ/app-monorepo pull request #2633
Opened 2023-02-27 16:04 UTC by sunnylqm

2023-03-02 07:17 UTC, loatheb requested changes

2023-03-02 07:17 UTC, loatheb commented on packages/kit/src/views/Discover/Explorer/Desktop/TabBarDesktop.tsx
> +    onPress={() => addNewWebTab()}
这些为什么都这样改，我看这个也不涉及到 this 指向问题，直接用函数不是会免去子组件每次 props 函数引用不一致的问题吗

2023-03-02 07:40 UTC, sidmorizon approved these changes, later dismissed

2023-03-02 07:40 UTC, sidmorizon commented on packages/kit/src/views/Discover/Explorer/Desktop/TabBarDesktop.tsx
> +    onPress={() => addNewWebTab()}
是因为会把 event 作为参数传给函数，函数再去把 event  dispatch action 了，可能导致报错。

严格一点用 useMemo 处理下比较好

2023-03-02 10:09 UTC, sunnylqm commented on packages/kit/src/views/Discover/Explorer/Desktop/TabBarDesktop.tsx
> +    onPress={() => addNewWebTab()}
fixed

2023-03-02 11:42 UTC, loatheb submitted a review, later dismissed

2023-03-06 00:37 UTC, kwoktung approved these changes, later dismissed

2023-03-06 09:08 UTC, originalix submitted a review, later dismissed

2023-03-06 12:17 UTC, ByteZhang1024 approved these changes

2023-03-06 13:17 UTC, kwoktung approved these changes

2023-03-07 00:54 UTC, originalix approved these changes

2023-03-07 00:54 UTC, merged