fix: market detail info view flexdirection OK-17774
OneKeyHQ/app-monorepo pull request #2645
Opened 2023-03-01 06:07 UTC by ezailWang

2023-03-01 06:59 UTC, sidmorizon commented on packages/kit/src/views/Market/Components/MarketDetail/MarketDetailComponent.tsx
> +        ? `${athDate.getFullYear()}-${
用 date-fns 来格式化日期

2023-03-02 05:11 UTC, sunnylqm approved these changes, later dismissed

2023-03-02 07:10 UTC, loatheb requested changes

2023-03-02 07:10 UTC, loatheb commented on packages/kit/src/views/Market/Components/MarketDetail/MarketDetailComponent.tsx
> +      athTime: ath ? dateFormat(athDate, 'yyyy-MM-dd') : undefined,
new Date 空字符串是 invalid Date 吧，这里用这种方式写呢 `athTime: dateFns.isValid(athDate) ? xx : xx` 上面就不要默认值了，确保 format 是个正常的值。

2023-03-02 07:32 UTC, sidmorizon submitted a review, later dismissed

2023-03-02 10:13 UTC, sunnylqm approved these changes

2023-03-02 11:19 UTC, ezailWang commented on packages/kit/src/views/Market/Components/MarketDetail/MarketDetailComponent.tsx
> +      athTime: ath ? dateFormat(athDate, 'yyyy-MM-dd') : undefined,
1

2023-03-02 11:43 UTC, loatheb approved these changes

2023-03-02 11:46 UTC, qwang1113 approved these changes

2023-03-02 11:46 UTC, merged