fix: ios overlay OK-18852 OK-18849
OneKeyHQ/app-monorepo pull request #2816
Opened 2023-04-06 08:48 UTC by sunnylqm

2023-04-06 12:06 UTC, loatheb requested changes

2023-04-06 12:06 UTC, loatheb commented on packages/kit/src/components/PermissionDialog/PermissionDialog.tsx
> -    android: IntentLauncher.ActivityAction.LOCATION_SOURCE_SETTINGS,
临上线这些改动是必要的吗？

2023-04-06 13:36 UTC, sunnylqm commented on packages/kit/src/components/PermissionDialog/PermissionDialog.tsx
> -    android: IntentLauncher.ActivityAction.LOCATION_SOURCE_SETTINGS,
路由的改动有必要全部回归一遍，这里是漏测的一个地方。这周建议先不发版

2023-04-07 02:53 UTC, originalix approved these changes

2023-04-07 03:25 UTC, loatheb approved these changes

2023-04-07 03:46 UTC, qwang1113 approved these changes

2023-04-07 03:46 UTC, merged