fix: fix validateAddress method（OK-20602）
OneKeyHQ/app-monorepo pull request #3114
Opened 2023-06-14 08:36 UTC by huhuanming

2023-06-14 09:10 UTC, originalix requested changes

2023-06-14 09:10 UTC, originalix commented on packages/engine/src/vaults/impl/sol/Vault.ts
> +      return Promise.resolve(address);
solana 的账户地址是否合法应该由 PublicKey.isOnCurve 函数来校验，因为 Keypaid 生成的地址总是会位于 ed25519 曲线上。

这个 issue 要解决的是 Token 地址不合法的问题，有单独的 vault method 来处理，不用改动账户地址校验的方法


```suggestion
  override validateAddress(address: string): Promise<string> {
    try {
      if (PublicKey.isOnCurve(address)) {
        return Promise.resolve(address);
      }
    } catch {
      // pass
    }
    return Promise.reject(new InvalidAddress());
  }

  override async validateTokenAddress(address: string): Promise<string> {
    try {
      return await this.validateAddress(address);
    } catch {
      const tokenAddress = new PublicKey(address);
      if (tokenAddress) {
        return address;
      }
      throw new InvalidAddress();
    }
  }
```

2023-06-14 09:12 UTC, originalix commented on packages/engine/src/vaults/impl/sol/Vault.ts
> +      return Promise.resolve(address);
https://stackoverflow.com/questions/71200948/how-can-i-validate-a-solana-wallet-address-with-web3js

2023-06-14 10:42 UTC, huhuanming commented on packages/engine/src/vaults/impl/sol/Vault.ts
> +      return Promise.resolve(address);
了解了

2023-06-14 11:17 UTC, originalix commented on packages/engine/src/vaults/impl/sol/Vault.ts
> +      return Promise.resolve(address);
或者简单点 validateTokenAddress 直接 new PublicKey 来判断即可

2023-06-14 12:19 UTC, huhuanming commented on packages/engine/src/vaults/impl/sol/Vault.ts
> +      return Promise.resolve(address);
okay 改好啦 😆

2023-06-14 15:13 UTC, somebodyLi commented on packages/engine/src/vaults/impl/sol/Vault.ts
> +      return Promise.resolve(address);
这个地方这样做还是不太稳妥，现在的做法校验ata可能还行，但是mint address还是用api更稳妥 `getAccountInfo`, 看下响应中的owner字段是不是 `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`

2023-06-15 02:27 UTC, originalix commented on packages/engine/src/vaults/impl/sol/Vault.ts
> +      return Promise.resolve(address);
跟 @somebodyLi  讨论了下，这块维持 new PublicKey 的判断就可以了

2023-06-15 02:28 UTC, originalix approved these changes

2023-06-15 03:45 UTC, qwang1113 submitted a review, later dismissed

2023-06-15 06:13 UTC, sidmorizon submitted a review, later dismissed

2023-06-15 06:23 UTC, originalix approved these changes, later dismissed

2023-06-15 13:12 UTC, sunnylqm commented
@huhuanming The base branch requires all commits to be signed

2023-06-15 13:18 UTC, huhuanming commented
> @huhuanming The base branch requires all commits to be signed

😂

2023-06-15 13:50 UTC, sunnylqm approved these changes

2023-06-16 01:05 UTC, weatherstar approved these changes

2023-06-16 02:31 UTC, originalix approved these changes

2023-06-16 08:23 UTC, merged