feat: support batch transfer on btc/btc fork chain OK-19443
OneKeyHQ/app-monorepo pull request #3128
Opened 2023-06-16 08:59 UTC by weatherstar

2023-06-16 09:59 UTC, originalix requested changes

2023-06-16 09:59 UTC, originalix commented on packages/engine/src/vaults/utils/btcForkChain/VaultBtcFork.ts
> +    });
这段筛选可用 UTXO，进行 CoinSelect 的逻辑应该是统一的，抽函数来复用吧，以免之后为了 Ordinals 的业务逻辑对 Coin Control 部分有逻辑调整会有修改遗漏的地方

2023-06-16 09:59 UTC, originalix commented on packages/engine/src/vaults/utils/btcForkChain/VaultBtcFork.ts
> +
这里读起来有点奇怪：
- 如果 outputs 里有包含不给自己的转账，就只展示没有自己转账部分的 output
- 如果 outputs 只有给自己的转账时才展示一个 output 的解析

如果一个 output 里的情况是这样的呢：有几笔给自己地址的转账，也有几笔给其他地址的转账，并且这笔交易的方向被判定为发送，这时候该怎么展示呢

2023-06-19 00:37 UTC, weatherstar commented on packages/engine/src/vaults/utils/btcForkChain/VaultBtcFork.ts
> +
我的理解是一个发送交易如果有转给自己地址的 output，很难判定是批量转账手动添加的 output 还是找零产生的 output，那么结果就是要么都显示要么都过滤。
我在这里的考虑是批量转账给自己的地址不是一个常规的高频操作，但是普通转账产生给自己的地址的找零 output 几乎每个转账交易都会有，相比较之下都过滤掉会更好一些。这里有办法区分吗，如果我理解有误的话请纠正我

2023-06-19 14:07 UTC, originalix approved these changes

2023-06-19 14:41 UTC, kwoktung approved these changes

2023-06-20 01:14 UTC, ByteZhang1024 approved these changes

2023-06-20 01:22 UTC, merged