refactor: eth sign message methods OK-20734
OneKeyHQ/app-monorepo pull request #3155
Opened 2023-06-27 00:47 UTC by weatherstar

2023-06-28 11:04 UTC, loatheb requested changes

2023-06-28 11:04 UTC, loatheb commented on packages/shared/src/utils/messageUtils.ts
> +    [message, from] = payload as [string, string];
这里为什么是这样，上面 payload 默认给空对象，但是下面又解构数组

2023-06-28 13:53 UTC, weatherstar commented on packages/shared/src/utils/messageUtils.ts
> +    [message, from] = payload as [string, string];
fixed

2023-06-29 01:30 UTC, loatheb requested changes

2023-06-29 01:30 UTC, loatheb commented on packages/shared/src/utils/messageUtil.test.ts
> +      const from = '0x3244e191f1b4903970224322180f1fbbc415696b';
这块的用例不全吧，我刚看 mm 这里的好多我们都还没有 https://github.com/MetaMask/eth-sig-util/blob/main/src/sign-typed-data.test.ts

2023-06-29 13:14 UTC, weatherstar commented on packages/shared/src/utils/messageUtil.test.ts
> +      const from = '0x3244e191f1b4903970224322180f1fbbc415696b';
fixed

2023-07-06 02:19 UTC, sidmorizon approved these changes, later dismissed

2023-07-06 02:19 UTC, sidmorizon commented on packages/shared/src/utils/messageUtils.ts
> +export function validateTypedSignMessageDataV1(
建个issue，tx 也需要类似的校验逻辑，避免上次的参数错误给用户发出了一笔新建合约的交易，导致资金损失

2023-07-06 03:20 UTC, huhuanming requested changes, later dismissed

2023-07-06 03:20 UTC, huhuanming commented on packages/blockchain-libs/src/provider/chains/eth/provider.ts
> +    debugger;
debugger 得删掉 😂

2023-07-08 02:06 UTC, weatherstar commented on packages/shared/src/utils/messageUtils.ts
> +export function validateTypedSignMessageDataV1(
ok

2023-07-08 02:06 UTC, weatherstar commented on packages/blockchain-libs/src/provider/chains/eth/provider.ts
> +    debugger;
fix

2023-07-09 23:53 UTC, loatheb approved these changes

2023-07-10 07:45 UTC, sidmorizon approved these changes

2023-07-10 08:10 UTC, ByteZhang1024 approved these changes

2023-07-10 23:49 UTC, merged