Fix: cosmos dApp OK-20959 OK-21026 OK-20997
OneKeyHQ/app-monorepo pull request #3190
Opened 2023-07-05 15:33 UTC by ByteZhang1024

2023-07-06 01:46 UTC, sidmorizon approved these changes, later dismissed

2023-07-06 04:27 UTC, kwoktung submitted a review, later dismissed

2023-07-07 03:11 UTC, originalix submitted a review, later dismissed

2023-07-07 04:45 UTC, qwang1113 requested changes

2023-07-07 04:45 UTC, qwang1113 commented on packages/kit/src/views/Wallet/Tools/index.tsx
> +        openAddressDetails(
这里需要用 selectedNetwork, 在 allNetworks 下是先点击 item, 弹出选择 network modal, 然后再触发, 也就是说当前的 network 不一定是正确的, https://www.figma.com/file/vKm9jnpi3gfoJxZsoqH8Q2/%F0%9F%91%A4-Account-%26-Portfolio?type=design&node-id=17609-184897&mode=design&t=15MdcXGpDbdyvhol-0

2023-07-07 06:47 UTC, qwang1113 submitted a review, later dismissed

2023-07-08 06:53 UTC, sidmorizon submitted a review, later dismissed

2023-07-09 01:12 UTC, weatherstar submitted a review, later dismissed

2023-07-10 03:29 UTC, originalix approved these changes

2023-07-10 03:29 UTC, linleiqin approved these changes

2023-07-10 03:30 UTC, kwoktung approved these changes

2023-07-10 03:43 UTC, merged