feat: webembed webview api
OneKeyHQ/app-monorepo pull request #3477
Opened 2023-08-31 03:45 UTC by sidmorizon

2023-09-01 03:11 UTC, originalix commented on packages/kit-bg/src/webembeds/instance/webembedApiProxy.ts
> +  }
这里可以理解为 App 启动时就会启用一个常驻的 WebEmbedApiWebview 容器，所以不再需要 Ready 检查了么

2023-09-01 06:00 UTC, sidmorizon commented on packages/kit-bg/src/webembeds/instance/webembedApiProxy.ts
> +  }
proxy 这一层不需要检查，background 层会检查并等待
packages/kit-bg/src/providers/ProviderApiPrivate.ts -> callWebEmbedApiProxy

2023-09-01 06:12 UTC, originalix commented on packages/kit-bg/src/webembeds/instance/webembedApiProxy.ts
> +  }
原来是通过 webEmbedApiReady 的方法通信来确保跟 WebView 通信正常，那确实是更靠谱了 👍

之前只是用 onWebViewRef 来确认 WebView 加载成功就认为是 Ready 状态了

2023-09-01 06:13 UTC, originalix approved these changes, later dismissed

2023-09-01 06:19 UTC, weatherstar approved these changes, later dismissed

2023-09-03 06:32 UTC, huhuanming commented on packages/components/src/OverlayContainer/index.tsx
> +      testID="OverlayContainer-View-775187"
775187 有什么特殊含义吗 😳

2023-09-03 06:40 UTC, huhuanming requested changes

2023-09-03 06:40 UTC, huhuanming commented on packages/components/src/Select/Container/Mobile.tsx
> +        testID="SelectContainerMobile-ModalizeBox-914856"
😳 这些number 是怎么定的呢？
会不会影响 qa 的自动化测试？

2023-09-03 06:40 UTC, huhuanming commented on packages/engine/src/index.ts
> +      if (result) {
是个空 if。
要不要为这个 if 语句添加个 log 或者去掉

2023-09-03 06:40 UTC, huhuanming commented on packages/kit-bg/src/webembeds/.gitkeep
这个空文件需要提交吗？

2023-09-04 01:24 UTC, sidmorizon commented on packages/components/src/Select/Container/Mobile.tsx
> +        testID="SelectContainerMobile-ModalizeBox-914856"
不影响，这个之前本来也没有，给一个随机数方便检索，避免重名的情况，后面也不会去改

2023-09-04 01:25 UTC, sidmorizon commented on packages/components/src/Select/Container/Mobile.tsx
> +        testID="SelectContainerMobile-ModalizeBox-914856"
自动化测试如果受到影响会调整，比如组件命名发生变更，组件层级变更，这些操作都会很多，不仅仅是 testID

2023-09-04 07:49 UTC, closed without merging