feat: nestScrollView to tamagui
OneKeyHQ/app-monorepo pull request #3563
Opened 2023-09-20 01:55 UTC by ByteZhang1024

2023-09-20 02:38 UTC, loatheb requested changes

2023-09-20 02:38 UTC, loatheb commented on packages/components/src/CollapsibleTabView/TabContainerNative.tsx
> +import type { OnPageChangeEvent } from '@onekeyhq/app/src/views/NestedTabView/types';
为什么需要从 app 目录导入？

2023-09-20 02:38 UTC, loatheb commented on packages/components/src/CollapsibleTabView/TabContainerNative.tsx
> +  const onRefreshCallBack = useCallback(() => {
这些所有的内容都测试过性能吗？确定每一部分的代码都是必要的吗？

2023-09-20 02:46 UTC, ByteZhang1024 commented on packages/components/src/CollapsibleTabView/TabContainerNative.tsx
> +import type { OnPageChangeEvent } from '@onekeyhq/app/src/views/NestedTabView/types';
和 Native 的链接都放在 app 了

2023-09-20 02:49 UTC, loatheb commented on packages/components/src/CollapsibleTabView/TabContainerNative.tsx
> +import type { OnPageChangeEvent } from '@onekeyhq/app/src/views/NestedTabView/types';
不能都统一放到 components 目录里面吗？

2023-09-22 03:05 UTC, ByteZhang1024 commented on packages/components/src/CollapsibleTabView/TabContainerNative.tsx
> +  const onRefreshCallBack = useCallback(() => {
需要的，切换黑暗模式，要改颜色。

2023-09-26 02:06 UTC, huhuanming approved these changes

2023-10-12 12:35 UTC, closed without merging