Feat/x jotai
OneKeyHQ/app-monorepo pull request #3745
Opened 2023-10-31 09:27 UTC by sidmorizon

2023-10-31 11:21 UTC, huhuanming commented
辛苦看看
```shell
[node] Warnings Counts: 827
[node] Please do not add more ESLint warnings than 730
[node] Hope you can fix the ESLint warings introduced after this merge.
```

2023-10-31 13:14 UTC, originalix requested changes

2023-10-31 13:14 UTC, originalix commented on packages/kit-bg/src/states/jotai/jotaiBgSync.ts
> +  }
这俩函数体内的内容一致

2023-10-31 13:14 UTC, originalix commented on packages/kit-bg/src/states/jotai/utils/wrapAtomPro.ts
> +      }
这段的逻辑有问题，baseAtom.initialValue 应该读取出一个 undefined

对于一个 PrimitiveAtom，它的初始值属性是 init；对于其他 computed atom，貌似连 init 属性也没有了

```
type WithInitialValue<Value> = {
    init: Value;
};
```

2023-10-31 13:18 UTC, originalix commented on packages/kit-bg/src/states/jotai/utils/wrapAtomPro.ts
> +      }
以及下面这段代码可能得对 RESET 做一下类型兼容

```ts
return {
    target: new JotaiCrossAtom(name, atomBuilder),
    // eslint-disable-next-line react-hooks/rules-of-hooks
    use: () => useAtom(atomBuilder() as ReturnType<T>),
};
```

否则 RESET 时肯定报类似错误

```
const [, setPrice] = useDemoPriceAtom();
setPrice(RESET); // 'RESET' is not assignable to parameter of type 'SetStateAction<number>'
```

2023-11-01 01:30 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/jotaiBgSync.ts
> +  }
jotaiUpdateFromUi 不用了

2023-11-01 04:48 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/utils/wrapAtomPro.ts
> +      }
fixed

2023-11-01 05:04 UTC, originalix approved these changes, later dismissed

2023-11-01 06:20 UTC, huhuanming submitted a review, later dismissed

2023-11-01 13:28 UTC, huhuanming approved these changes

2023-11-01 15:56 UTC, originalix approved these changes

2023-11-02 02:58 UTC, ezailWang approved these changes

2023-11-02 02:58 UTC, merged