Feat/password component
OneKeyHQ/app-monorepo pull request #3753
Opened 2023-11-02 07:49 UTC by ezailWang

2023-11-02 11:22 UTC, sidmorizon commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +    return true;
拋异常，密码没有设置，不应该返回true

2023-11-02 11:22 UTC, sidmorizon commented on packages/kit-bg/src/dbs/local/indexed/LocalDbIndexed.ts
> +    return this.readyDb.then(
用 await 语法，不要用 promise then

2023-11-02 11:22 UTC, sidmorizon commented on packages/kit-bg/src/dbs/local/indexed/LocalDbIndexed.ts
> +          const transaction = db.transaction(
参考getBackupUUID如何增删改查

2023-11-02 11:22 UTC, sidmorizon commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +  checkPassword(context: OneKeyContext, password: string): boolean {
为什么要改，就是希望外部调用的时候轻松些

2023-11-02 15:14 UTC, ezailWang commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +  checkPassword(context: OneKeyContext, password: string): boolean {
之前的实现，getContext -> verifyPassword -> checkPassword 循环调用了。
外部直接调用 verifyPassword 就好了

2023-11-02 15:14 UTC, ezailWang commented on packages/kit-bg/src/dbs/local/indexed/LocalDbIndexed.ts
> +          const transaction = db.transaction(
1

2023-11-02 15:14 UTC, ezailWang commented on packages/kit-bg/src/dbs/local/indexed/LocalDbIndexed.ts
> +    return this.readyDb.then(
1

2023-11-02 15:34 UTC, ezailWang commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +    return true;
1

2023-11-03 01:56 UTC, sidmorizon commented on packages/kit-bg/src/dbs/local/indexed/LocalDbIndexed.ts
> +    if (!this.checkPassword(context, oldPassword)) {
在 service 层的方法上用 verifyPassword ，自带 throw error，节约 db 层的代码，db 层只负责读写数据

2023-11-03 01:56 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +    const enCodedPassword = encrypt(
```suggestion
    const encodedPassword = encrypt(
```

2023-11-03 01:56 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +    oldPassword: string,
数据校验在 service 层做，db 层只关心数据读写。
需要校验 oldPassword 不为空且密码正确。

2023-11-03 01:56 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +    const enCodedOldPassword = encodeSensitiveText({ text: oldPassword });
oldPassword 和 newPassword 应该在 UI 层发送之前，已经做好了 encode 再传给 background，而不是明文传输给background ，让 background 来 encode

2023-11-03 02:02 UTC, sidmorizon approved these changes, later dismissed

2023-11-03 02:02 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +  async setCachedPassword(password: string): Promise<string> {
所有函数参数上的 password 必须是已经 encode 过再传入的，encode 有现成的方法 encodePassword，background 可以直接用。 禁止明文传递 password。

写一个校验方法，ensurePasswordSensitiveEncoded ，在每个方法之前判断一下

2023-11-03 02:02 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +      return cachedPassword;
返回值不需要明文，直接返回密文就行

2023-11-03 02:52 UTC, sidmorizon commented on packages/kit/src/components/Password/PasswordSetup.tsx
> +              await savePassword(updatePasswordRes);
这个方法放到 service 里统一管理，单独用 utils 很难发现这个逻辑

2023-11-03 02:52 UTC, sidmorizon commented on packages/kit/src/components/Password/PasswordSetup.tsx
> +  const { isSupportBiologyAuth, setBiologyAuthEnable, enableBiologyAuth } =
写入方法放到 service password 管理

2023-11-03 02:52 UTC, sidmorizon commented on packages/kit/src/components/Password/PasswordVerify.tsx
> +} from '../../utils/localAuthentication';
放到 servicePassword 管理

2023-11-03 02:52 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +      biologyAuthEnable: false,
isBiologyAuthEnabled

2023-11-03 02:52 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +      passwordSet: false,
isPasswordSetted

2023-11-03 09:08 UTC, ezailWang commented on packages/kit/src/components/Password/PasswordSetup.tsx
> +  const { isSupportBiologyAuth, setBiologyAuthEnable, enableBiologyAuth } =
类似这种生物识别的 settings 用一个统一的 hook 管理比较方便吧，后续在 settings 列表里面有用到，单独的开启手势这种，其实是跟密码解耦的，就是密码这块有一个这个开关，这里不涉及密码的读写，密码的读写全部在 service 里面进行，其实就两个函数暴露出去，一个生物识别验证一个输入验证。

2023-11-03 09:10 UTC, ezailWang commented on packages/kit-bg/src/services/ServicePassword.ts
> +  async setCachedPassword(password: string): Promise<string> {
缓存就只是在保存之前验证一下密码，不做加解密操作，如果是明文是无法验证通过

2023-11-06 04:15 UTC, huhuanming requested changes

2023-11-06 04:15 UTC, huhuanming commented on packages/kit/src/views/Swap/index.tsx
> +            // setOpen(!open);
有没有可能有 fail 的情况，异常处理是否需要暴露？😳

2023-11-06 04:15 UTC, huhuanming commented on packages/kit/src/hooks/useBiologyAuthSettings.tsx
> +
hooks 从 components 里面导入 module，感觉不是很合理😳
容易引发循环引用

2023-11-06 04:15 UTC, huhuanming commented on packages/kit/src/hooks/useBiologyAuthSettings.tsx
> +      .catch(() => {});
faceid 或者 touchid 不可用的时候需要 catch 提示吗？
![image](https://github.com/OneKeyHQ/app-monorepo/assets/5743863/8663d51d-f5d7-4830-b354-01f43b68dd4b)

2023-11-06 04:15 UTC, huhuanming commented on packages/kit/src/views/Swap/index.tsx
> +      <YStack space="@4">
印象里，tamagui 只有$语法呢？😳

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +} from '@onekeyhq/kit/src/components/BioloygAuth';
kit-bg 不能反向引用 kit 的组件，共享的业务逻辑写到 shared 里

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +    const verified = await this.verifyPassword(oldPassword);
这段逻辑统一成一个函数， validatePassword
- 检查密码是否为空
- 检查密码强度
- 检查其他密码规则
- 检查密码是否正确（ db 层的 verifyPassword 要放在最后）

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +    await this.validatePasswordStrength(password);
同理，这里用 validatePassword 先验一遍，否则空密码也允许执行了

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword.ts
> +  async setPassword(password: string): Promise<string> {
加一个 TODO ，创建密码时，需要先将现有所有 db 的 助记词和私钥清空，因为这些都是上次密码的加密数据。

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit/src/components/BioloygAuth/index.native.tsx
> +  let text = await getItemAsync('password');
这两个文件有90%代码相似度，应该是把 storage 部分给剥离出 utils。 参考 appStorage 的做法，封装

secureStorage.getSecureItem
secureStorage.setSecureItem
secureStorage.removeSecureItem

然后在 native 和 desktop 下用不同的文件后缀名实现

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit/src/components/Password/PasswordUpdate.tsx
> +      if (data.oldPassword === data.newPassword) {
数据校验的业务逻辑写到 service 层，UI 层不要有，DB 层也不要有。把执行结果返回，由 UI 做提示

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit/src/hooks/useBiologyAuthSettings.tsx
> +  const enableBiologyAuth = useMemo(
使用 globalAtomComputed

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit/src/hooks/useBiologyAuthSettings.tsx
> +  const [isSupportBiologyAuth, setIsSupportBiologyAuth] = useState(false);
这个状态会变化两次，初次为 false，后面再变成 true，假如业务代码执行比这个变化更快，那么就会出问题

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit/src/components/BioloygAuth/index.tsx
>  export const localAuthenticate: () => Promise<LocalAuthenticationResult> = () =>
直接到放到 service 里执行

2023-11-06 04:37 UTC, sidmorizon commented on packages/kit/src/hooks/useBiologyAuthSettings.tsx
> +  const setBiologyAuthEnable = useCallback(
直接放到 service 里执行

2023-11-06 15:48 UTC, ezailWang commented on packages/kit/src/views/Swap/index.tsx
> +            // setOpen(!open);
fail的情况在里面处理了，业务逻辑不需要关系密码验证，只需要拿到密码即可，如果没拿到就走不下去。

2023-11-06 15:49 UTC, ezailWang commented on packages/kit/src/hooks/useBiologyAuthSettings.tsx
> +      .catch(() => {});
修改了写法，现在会保存在jotai中

2023-11-06 15:50 UTC, ezailWang commented on packages/kit/src/views/Swap/index.tsx
> +      <YStack space="@4">
1

2023-11-07 02:32 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +  isBiologyAuthEnable: boolean;
只有基础状态需要声明在这里，计算状态不需要

2023-11-07 02:32 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +export const {
这三个 computed atom 可以合并声明为一个，只读

isBiologyAuthEnable 改成 isBiologyAuthSwitchOn 还是单独声明基础 atom，作为开关更新的操作

```
const {
  target: settingsBiologyAuthInfoAtom,
  use: useSettingsBiologyAuthInfoAtom,
} = globalAtomComputed(async ()=> {
   return { authType, isSupport, isSwitchOn,  isEnable: isBiologyAuthSwitchOn && isSupport  }
})

```

2023-11-07 02:32 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.desktop.ts
> +export const isSupportBiologyAuth = () =>
用 memoizee 永久缓存这个函数的结果，下次就不用执行

2023-11-07 02:32 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.native.ts
> +export const isSupportBiologyAuth = () =>
memoizee 缓存结果

2023-11-07 02:36 UTC, sidmorizon commented on packages/shared/src/storage/secureStorage/index.ts
> +export const setSecureItem = async (key: string, data: string) =>
声明共享的 types，三个 index 使用 同一个 type 导出

```suggestion
import { ISecureStorage } from './types'

const storage: ISecureStorage = {
    setSecureItem,
    getSecureItem,
    removeSecureItem,
}
export default storage
```

2023-11-07 02:37 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.ts
> +import type {
通 secureStorage，使用共享 types 约束多平台的方法参数和返回值

2023-11-08 01:52 UTC, originalix commented on packages/core/src/secret/encryptors/aes256.ts
> +  password = decodePassword({ password });
直接换参数名是不是更直观一点

2023-11-08 01:52 UTC, originalix commented on packages/kit/src/components/Password/container/PasswordUpdateContainer.tsx
> +        const enCodeOldPassword =
encode

2023-11-08 01:52 UTC, originalix commented on packages/kit/src/components/Password/container/PasswordVerifyContainer.tsx
> +        const enCodePassword = encodePassword({ password: data.password });
encode

2023-11-08 02:05 UTC, sidmorizon commented on packages/shared/src/storage/secureStorage/index.ts
> +import type { ISecureStorage } from './typrs';
types

2023-11-08 02:05 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +} = globalAtom({
IsBiologyAuthSwitchOn 这个状态合并到上面的 settings 里，不用单独声明，只有高频数据和computed数据需要单独声明，具体查看 [jotai 的 wiki ](https://onekeyhq.atlassian.net/wiki/spaces/ONEKEY/pages/343572485/-#Jotai-Global-%E5%85%A8%E5%B1%80%E7%8A%B6%E6%80%81%E5%AE%B9%E5%99%A8%EF%BC%88%E6%9B%BF%E4%BB%A3-Redux%EF%BC%89)

2023-11-08 02:05 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +  target: settingsBiologyAuthInfoAtom,
BiologyAuthInfo 和 PromptPromise 单独用新文件 atoms/password.ts , 因为这两个状态和 settings 无关，和 密码有关

2023-11-08 02:05 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +} = globalAtom<ISettingsPromptPromiseAtom>({
此命名不够具体，PromptPromise 看上去是一个通用提示框的状态标识，但是实际业务里只和密码提示框有关系，除非这个状态打算做成一个通用的提示框，和具体业务无关

建议命名：  usePassword = {  passwordVerifyPromptId: number | undefined }

2023-11-08 02:05 UTC, sidmorizon commented on packages/kit/src/components/Password/container/PasswordVerifyPromptMount.tsx
> +    if (promiseId) {
建议用 !isNil , 因为 promiseId 为 0 也是合法的

2023-11-08 02:06 UTC, sidmorizon commented on packages/core/src/secret/encryptors/aes256.ts
> +  password = decodePassword({ password });
`passwordDecoded = decodePassword({ password });`

2023-11-08 02:16 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +  isBiologyAuthSupported?: boolean;
这个不需要

2023-11-08 02:27 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.native.ts
> +const isSupportBiologyAuth = memoizee(isSupportBiologyAuthFn);
异步函数要加 promise: true ，否则 cache 不住

2023-11-08 02:27 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.native.ts
> +const isSupportBiologyAuthFn = () =>
尽量用 async await 语法，不要用 promise then 回调地狱
```
async ()=>{
const supported  = await hasHardwareAsync()
const isEnrolled = await isEnrolledAsync();
return supported && isEnrolled

}
```

2023-11-08 02:37 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.desktop.ts
> +      return {
```suggestion
      result.success ? {success: true} : {success:false, error: result.error || 'biologyAuthenticate failed'}
```

2023-11-08 02:37 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.desktop.ts
> +      return { success: false, error: 'no supported' };
使用catch的error.message,而不是写死的 no supported

2023-11-08 02:37 UTC, sidmorizon commented on packages/shared/src/biologyAuth/index.desktop.ts
> +      return { success: false, error: 'no supported' };
error message 需要指明具体业务，否则日志可读性不好： biologyAuthenticate not supported

2023-11-08 06:33 UTC, huhuanming approved these changes, later dismissed

2023-11-08 07:10 UTC, sidmorizon approved these changes, later dismissed

2023-11-08 07:10 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atomNames.ts
> +  passwordPromptPromiseAtom = 'passwordPromptPromiseAtom',
我的意思是这里直接用 passwordAtom 就行，不用在命名上指明具体业务，所有低频状态都往里面丢，和 settingsAtom 类似。只有高频数据需要单独定义，类似 settingsTimeNowAtom

2023-11-08 07:10 UTC, sidmorizon commented on packages/kit-bg/src/states/jotai/atoms/password.ts
> +export type IPasswordPromptPromiseAtom = {
用通用的 passwordAtom 命名就行，只有 computed 和 高频数据需要单独定义。

通用的低频数据放到第一行

2023-11-08 08:18 UTC, sidmorizon approved these changes, later dismissed

2023-11-08 09:05 UTC, originalix approved these changes

2023-11-08 09:06 UTC, huhuanming approved these changes

2023-11-08 09:14 UTC, sidmorizon approved these changes

2023-11-08 09:14 UTC, merged