feat: web3 browser
OneKeyHQ/app-monorepo pull request #3775
Opened 2023-11-08 08:00 UTC by originalix

2023-11-08 09:07 UTC, loatheb commented on packages/kit/src/views/Discovery/container/Browser/index.tsx
>    const isVerticalLayout = useIsVerticalLayout();
这个 hooks 已经不用了

2023-11-08 09:07 UTC, loatheb commented on packages/kit/src/views/Discovery/container/Context/contextWebTabs.ts
> +                  new URL(tabToModify.url ?? '').origin
这个是否考虑做到服务端？所有的 icon 都是 /favicon.ico 目录吗？

2023-11-08 09:47 UTC, originalix commented on packages/kit/src/views/Discovery/container/Context/contextWebTabs.ts
> +                  new URL(tabToModify.url ?? '').origin
这个 favicon 的获取会做在服务端，以前这种拼接 url 的方式不靠谱

2023-11-30 08:06 UTC, originalix commented on packages/kit/src/views/Discovery/container/Browser/index.tsx
>    const isVerticalLayout = useIsVerticalLayout();
Fixed

2023-12-01 02:57 UTC, huhuanming commented on packages/kit/src/routes/Root/Tab/TabNavigator.tsx
> +
这里我需要导出下 hooks，不能直接用 tamagui 的库 @huhuanming

2023-12-01 04:24 UTC, huhuanming requested changes
辛苦确认一下相关问题😳

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +    async () =>
下面使用 Promise 的话，这个 async 就没有意义了。
```javascript
async () => {
  const a = await A()
  return 1
}
```
和下面是等价的

```javascript
async () =>  new Promise((resolve) => {
    A().then((result) => {resolve(result)})
})
```
两种情况只保留一种就好。

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +        await takeScreenshot();
这里有点困惑。
我说说我的理解，就是截图是截取的 View 的视图。
那如果截取 View 的视图的话，感觉可以不用 await，可以让下面的路由先执行，这样交互上感觉反应更快。

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +      await takeScreenshot();
这里也是一样的疑问。

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +          disabled={displayHomePage ? true : !tab?.canGoBack}
应该等价于下面的情况。
```javascript
displayHomePage ||  !tab?.canGoBack
```

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/hooks/useBrowserOptionsAction.ts
> +    }, 300);
这里 300ms 是为啥呢？😳 会增加交互卡顿感。

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/components/WebView/InpageProviderWebView.desktop.tsx
> +    // const isVertical = useIsVerticalLayout();
这个参数看上去好像没有用了

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/container/Browser/DesktopBrowser.tsx
> +        headerRight={() => (
😳同文件抽个组件吧，就不用 eslint-disable 了

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/container/Browser/index.tsx
> +
这里我理解抽三个 broswer.native.tsx， broswer.desktop.tsx, broswer.tsx，就不用写那么多 if else 了。

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/container/Dashboard/Search.tsx
> +  }, [navigation]);
可以用 Page.Header 组件了 😳

2023-12-01 04:24 UTC, huhuanming commented on packages/kit/src/views/Discovery/container/Dashboard/Search.tsx
> +
这个 hooks 如果没有其他调试需求的话，感觉可以移除了

2023-12-04 01:58 UTC, originalix commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +          disabled={displayHomePage ? true : !tab?.canGoBack}
Fixed

2023-12-04 01:58 UTC, originalix commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +    async () =>
Fixed

2023-12-04 01:59 UTC, originalix commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +        await takeScreenshot();
是的，本来也是这么设计的

但是实际测试在 Android 端如果截图未完成直接就进行路由跳转在下个页面渲染时如果找不到对应的图片会有异常产生

2023-12-04 02:00 UTC, originalix commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +      await takeScreenshot();
原因同上，实际测试有问题

2023-12-04 02:01 UTC, originalix commented on packages/kit/src/views/Discovery/components/WebView/InpageProviderWebView.desktop.tsx
> +    // const isVertical = useIsVerticalLayout();
Removed

2023-12-04 02:04 UTC, originalix commented on packages/kit/src/views/Discovery/container/Browser/DesktopBrowser.tsx
> +        headerRight={() => (
Fixed

2023-12-04 04:29 UTC, originalix commented on packages/kit/src/views/Discovery/hooks/useBrowserOptionsAction.ts
> +    }, 300);
https://onekeyhq.atlassian.net/browse/OK-24790
不是的，这里有个 issue，延时反而让交互流畅了 🙈

2023-12-04 04:32 UTC, originalix commented on packages/kit/src/views/Discovery/container/Browser/index.tsx
> +
目前这么处理是可以的，看了下以前是因为要支持 iPad 布局才加了很多判断颠来倒去的

2023-12-04 04:32 UTC, originalix commented on packages/kit/src/views/Discovery/container/Dashboard/Search.tsx
> +  }, [navigation]);
已替换

2023-12-04 04:33 UTC, originalix commented on packages/kit/src/views/Discovery/container/Dashboard/Search.tsx
> +
Removed

2023-12-04 06:15 UTC, huhuanming commented on packages/kit/src/routes/Root/Tab/TabNavigator.tsx
> +
这个合进去之后我来清理

2023-12-04 06:15 UTC, huhuanming submitted a review, later dismissed

2023-12-04 08:39 UTC, huhuanming submitted a review, later dismissed

2023-12-04 12:01 UTC, loatheb requested changes

2023-12-04 12:01 UTC, revan-zhang commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntityBase.ts
> +        _tmpUpdatedAtText: new Date(updatedAt).toLocaleString(),
是不是应该尽可能避免使用 toLocaleString 这类自带 i18n 的方法，因为这个依赖的引擎有可能没实现，就需要额外 polyfill，在必要性不大的情况下其实感觉可以不用这类 API 级别的 i18n 方法。
以及这里 dev & desktop 增加 _tmpUpdatedAtText 是为了做什么？

2023-12-04 12:01 UTC, revan-zhang commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntityBase.ts
> +    this.updatedAt = updatedAt ?? 0;
updatedAt 为什么默认值是 0，最起码也是创建时候或者更新时候的时间戳

2023-12-04 12:01 UTC, revan-zhang commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +} from '../../../../views/Discovery/utils/explorerUtils';
对于这么长的 ../.. 还是建议直接使用绝对路径的

2023-12-04 12:01 UTC, revan-zhang commented on packages/kit/src/states/jotai/contexts/discovery/atoms.ts
> +  return tabs.length >= 20;
20 这个可能后面会根据机型动态调整，比如桌面端这种性能好点的多一些，移动端高端机型多一些，移动端低端机型少一些，最好提前整理个变量出来统一

2023-12-04 12:01 UTC, revan-zhang commented on packages/kit/src/views/Discovery/components/WebView/InpageProviderWebView.desktop.tsx
> +    const intervalRef = useRef<NodeJS.Timeout | null>(null);
这种还是尽量用 `ReturnType<typeof setTimeout>` 不依赖 NodeJS 这个包

2023-12-04 12:01 UTC, revan-zhang commented on packages/shared/src/consts/urlProtocolConsts.tsx
> +  `${ONEKEY_APP_DEEP_LINK_NAME}:` as const,
这个是什么意思？我们的发现页还允许打开 wc 这类协议吗？这里最好不要吧，就打开 https 且只能是 https 就行吧

2023-12-04 12:14 UTC, huhuanming commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntityBase.ts
> +        _tmpUpdatedAtText: new Date(updatedAt).toLocaleString(),
toLocaleString 的问题，现在一般推荐使用 Day.js。
另外使用 dayjs 的时候需要处理 local 切换，不用区域需要加载不同的地区日期语言包，可能还需要懒加载一下。
https://day.js.org/docs/en/i18n/changing-locale
————
这个问题，要不合进去后，我这里统一提供一个封装处理下，感觉更合适一点。

2023-12-04 12:15 UTC, huhuanming commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntityBase.ts
> +    this.updatedAt = updatedAt ?? 0;
updatedAt 通常默认情况下应该是创建时的时间戳。

2023-12-04 13:56 UTC, originalix commented on packages/kit/src/views/Discovery/components/WebView/InpageProviderWebView.desktop.tsx
> +    const intervalRef = useRef<NodeJS.Timeout | null>(null);
Fixed

2023-12-04 13:56 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/atoms.ts
> +  return tabs.length >= 20;
已抽取常量配置

2023-12-04 13:57 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +} from '../../../../views/Discovery/utils/explorerUtils';
全部扫了一遍替换了，不在 views/discovery 目录下的全部替换了

2023-12-04 14:02 UTC, originalix commented on packages/shared/src/consts/urlProtocolConsts.tsx
> +  `${ONEKEY_APP_DEEP_LINK_NAME}:` as const,
先仅有 https 了，其他 Deeplink 按需处理

2023-12-04 14:06 UTC, originalix commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntityBase.ts
> +    this.updatedAt = updatedAt ?? 0;
这里应该不用额外的 ?? 运算符 ，第 60 行有声明 updateAt 的值，不应该存在空值

2023-12-04 14:07 UTC, originalix commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntityBase.ts
> +        _tmpUpdatedAtText: new Date(updatedAt).toLocaleString(),
这个是迁移了 v4 的 SimpleDB 的逻辑，对比了一下之前 PR，应该是为了解决历史记录的 bug 额外增加的用来 debug 的，这里先移除了

2023-12-04 14:46 UTC, loatheb submitted a review, later dismissed

2023-12-05 01:07 UTC, loatheb approved these changes

2023-12-05 01:30 UTC, huhuanming approved these changes

2023-12-05 03:40 UTC, ezailWang approved these changes

2023-12-05 03:40 UTC, ezailWang commented on packages/kit/src/routes/Tab/TabNavigator.tsx
> +import { getTokenValue } from 'tamagui';
kit 里面不直接引用  tamagui 吧，getTokenValue 从 components 里面导出？

2023-12-05 03:41 UTC, originalix commented on packages/kit/src/routes/Tab/TabNavigator.tsx
> +import { getTokenValue } from 'tamagui';
全部标记给 @huhuanming 了，合入后他处理

2023-12-05 03:41 UTC, merged