style: iOS search bar icon color and placeholder color
OneKeyHQ/app-monorepo pull request #3802
Opened 2023-11-14 05:38 UTC by hellohublot

2023-11-14 06:05 UTC, huhuanming requested changes

2023-11-14 06:05 UTC, huhuanming commented on packages/components/src/SearchBar/index.tsx
> +      {...((value?.length ?? 0) > 0 && {
value?.length && 就行。。

不要 ((value?.length ?? 0) > 0

2023-11-14 06:45 UTC, hellohublot commented on packages/components/src/SearchBar/index.tsx
> +      {...((value?.length ?? 0) > 0 && {
@huhuanming Done

2023-11-15 01:01 UTC, originalix approved these changes

2023-11-15 10:57 UTC, loatheb approved these changes

2023-11-16 01:57 UTC, huhuanming approved these changes

2023-11-16 02:01 UTC, merged