Feat/app lock
OneKeyHQ/app-monorepo pull request #3805
Opened 2023-11-14 07:49 UTC by ezailWang

2023-11-15 12:58 UTC, originalix submitted a review, later dismissed

2023-11-17 02:39 UTC, sidmorizon commented on packages/kit-bg/src/services/ServicePassword/index.ts
> +  async unLockApp() {
把锁屏逻辑加上一起review，这样流程是完整的

2023-11-17 03:08 UTC, ezailWang commented on packages/kit-bg/src/services/ServicePassword/index.ts
> +  async unLockApp() {
1

2023-11-17 13:12 UTC, huhuanming requested changes

2023-11-17 13:12 UTC, huhuanming commented on packages/kit/src/components/AppLock/container/AppStateLockContainer.tsx
> +const AppStateLockContainer: FC<IAppStateLockContainerProps> = ({
类型可以用这样写
import type { FC, PropsWithChildren } from 'react';

const AppStateLockContainer: FC<PropsWithChildren<unknow>> =  ({

// 如果有其他类型定义，可以把 unknow 替换为其他类型
FC<PropsWithChildren<{ isVisible: boolean,  showFooter: boolean }>>

2023-11-21 00:45 UTC, sidmorizon approved these changes, later dismissed

2023-11-21 03:48 UTC, ezailWang commented on packages/kit/src/components/AppLock/container/AppStateLockContainer.tsx
> +const AppStateLockContainer: FC<IAppStateLockContainerProps> = ({
1

2023-11-21 03:50 UTC, huhuanming approved these changes

2023-11-21 03:50 UTC, originalix approved these changes

2023-11-21 04:01 UTC, sidmorizon approved these changes

2023-11-21 04:01 UTC, merged