fix: disabled the drag drop box of modalstack on the desktop
OneKeyHQ/app-monorepo pull request #3860
Opened 2023-11-23 03:06 UTC by hellohublot

2023-11-23 03:08 UTC, huhuanming requested changes

2023-11-23 03:08 UTC, huhuanming commented on packages/components/src/DesktopDragZoneBox/index.desktop.tsx
> +  disabled,
disabled 不太准确，用 draggable 更好一点 😳

2023-11-23 03:11 UTC, hellohublot commented on packages/components/src/DesktopDragZoneBox/index.desktop.tsx
> +  disabled,
@huhuanming 这里可能用 disabled 好一点哈
1. 第一个是因为 Pressable 自带这个属性
2. 第二个是因为 DesktopDragZoneBox 本身就是一个拖动组件, 再有一个是否拖动属性有点奇怪哦，<DesktopDragZoneBox disabled ={false}> 看起来比 <DesktopDragZoneBox draggable={false}> 好一点哈

2023-11-23 04:14 UTC, huhuanming commented on packages/components/src/DesktopDragZoneBox/index.desktop.tsx
> +  disabled,
有道理 😳

2023-11-23 04:14 UTC, huhuanming approved these changes

2023-11-24 01:15 UTC, loatheb approved these changes

2023-11-24 02:50 UTC, originalix approved these changes

2023-11-24 02:50 UTC, merged