refactor: refact Splash component &  Support dark mode
OneKeyHQ/app-monorepo pull request #3867
Opened 2023-11-27 11:27 UTC by huhuanming

2023-11-27 12:33 UTC, loatheb requested changes

2023-11-27 12:33 UTC, loatheb commented on packages/shared/src/web/index.html.ejs
> -
把 index.html 里面的 splash screen 去掉有可能加载 JS 非常久导致 web 端看不到启动的 logo

2023-11-27 13:15 UTC, huhuanming commented on packages/shared/src/web/index.html.ejs
> -
处理好啦，顺带简化了下过去的代码。

2023-11-27 13:16 UTC, huhuanming commented on packages/shared/src/web/index.html.ejs
> -
后续改造下，应该直接使用这个 ejs 文件，不该再继续复制为 html 文件了

2023-11-28 01:54 UTC, sidmorizon approved these changes

2023-11-28 02:08 UTC, originalix approved these changes

2023-11-28 06:21 UTC, ezailWang approved these changes

2023-11-28 06:25 UTC, huhuanming reviewed
修改了

2023-11-28 06:27 UTC, loatheb approved these changes

2023-11-28 06:27 UTC, merged