feat: overview
OneKeyHQ/app-monorepo pull request #3873
Opened 2023-11-28 01:13 UTC by weatherstar

2023-12-14 02:04 UTC, sidmorizon commented on packages/shared/types/gas.ts
> +  fees: IEIP1559Fee[] | string[];
参考  ITxUpdateFeeInfo 来定义手续费
```
export interface ITxUpdateFeeInfo {
  gas?: {
    gasPrice?: string; // chainValue not GWEI
    gasLimit?: string; // chainValue not GWEI
    // gas?: string; // alias for gasLimit
  };
  gasEIP1559?: {
    gasPrice?: string; // chainValue not GWEI
    maxFeePerGas?: string; // chainValue not GWEI
    maxPriorityFeePerGas?: string; // chainValue not GWEI
  };
}
```

2023-12-14 02:04 UTC, sidmorizon commented on packages/shared/types/gas.ts
> +  fees: IEIP1559Fee[] | string[];
不同的手续费格式使用不同的字段来表示，而不是共享同一个字段，导致使用过程中，需要复杂的 if 和 as 来做转化

2023-12-14 02:04 UTC, sidmorizon commented on packages/shared/types/gas.ts
> +  fees: IEIP1559Fee[] | string[];
使用不同的字段，可以大大简化调用方的判断逻辑，因为判断类型和取值都是使用同一个字段

2023-12-14 02:34 UTC, weatherstar commented on packages/shared/types/gas.ts
> +  fees: IEIP1559Fee[] | string[];
这里 fees 是服务端接口返回的字段，前端拿到结果后做了一次转换到 price 和 price1559。这里是需要直接在服务端处理再返回么？如果是在前端处理的话，这里类型 IFeeInfoUnit 定义和 ITxUpdateFeeInfo 我统一一下

2023-12-18 05:52 UTC, originalix commented on packages/kit-bg/src/services/ServiceDefi.ts
> +    const endpoint = await getBaseEndpoint();
看后面每个 API 调用都要多写一行 `const endpoint = await getBaseEndpoint();`，可以处理在一个类似 getClient 的函数里

2023-12-18 05:52 UTC, originalix commented on packages/kit-bg/src/vaults/base/VaultBase.ts
> +  }
这段 debug 逻辑感觉已经不需要了

2023-12-18 08:43 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceDefi.ts
> +    const endpoint = await getBaseEndpoint();
fixed

2023-12-18 08:43 UTC, weatherstar commented on packages/kit-bg/src/vaults/base/VaultBase.ts
> +  }
fixed

2023-12-18 13:16 UTC, loatheb requested changes

2023-12-18 13:16 UTC, loatheb commented on packages/kit-bg/src/endpoints/endpointsMap.ts
> +  base: {
这里除了 base 还会有什么？

2023-12-18 13:16 UTC, loatheb commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +    const NAME_RESOLVER = [
这个不需要了吧，都是服务端获取了

2023-12-18 13:16 UTC, loatheb commented on packages/kit-bg/src/services/ServiceBase.ts
> +      this._client = axios.create({
是怎么通用的处理 request 通用 header，response 通用的 message 结构的呢

2023-12-18 13:32 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceBase.ts
> +      this._client = axios.create({
在 axiosInterceptor.ts 里处理

2023-12-18 13:34 UTC, loatheb requested changes

2023-12-18 13:34 UTC, loatheb commented on packages/kit/src/hooks/useFormOnChangeDebounced.ts
> +import { useEffect, useRef, useState } from 'react';
这个是组件相关的需求吧

2023-12-18 13:34 UTC, loatheb commented on packages/kit/src/hooks/useFormatData.ts
> +import { useCallback, useMemo } from 'react';
这些我怎么感觉都不需要，放到后端处理呢？前端直接渲染字符串就行，而且这里没有响应式的需求，封装 hooks 的优势在哪

2023-12-18 13:34 UTC, weatherstar commented on packages/kit-bg/src/endpoints/endpointsMap.ts
> +  base: {
wss 或者其他可能的 endpoint

2023-12-18 13:36 UTC, loatheb commented on packages/kit-bg/src/endpoints/endpointsMap.ts
> +  base: {
那不如直接用 prod / test 做 key，这样也能和前端 store 存的内容对应上。
```
{
  test: {
    http: '',
    websocket: '',
  },
  prod: {
    http: '',
    websocket: '',
  },
}
```

2023-12-18 13:36 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +    const NAME_RESOLVER = [
这里保留 pattern 是想减少服务端请求，如果域名验证不通过就不会像服务端发送请求。否则输入框的变动都会去请求域名解析接口。

2023-12-18 13:39 UTC, loatheb commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +    const NAME_RESOLVER = [
保留两套那就会有两套规则了，服务端以后就没法扩展了，以后那也会出现新增了一个域名后缀前端没有匹配的情况。这里只要加好 debounce 统一都从服务端获取就可以

2023-12-18 13:46 UTC, loatheb requested changes

2023-12-18 13:46 UTC, loatheb commented on packages/components/src/layouts/Page/PageFooterActions.tsx
> +  onConfirm?: () => void | Promise<boolean> | Promise<void>;
这里这类改动和需求 @huhuanming 确认下呢

2023-12-18 13:46 UTC, loatheb commented on packages/kit-bg/src/endpoints/index.tsx
> +  const settings = await settingsPersistAtom.get();
得确保接口的请求都在 store 初始化之后，否则这里保存的信息可能会不生效读取默认值？

2023-12-18 13:46 UTC, loatheb commented on packages/kit-bg/src/vaults/base/VaultBase.ts
> +import { isEmpty, isNil } from 'lodash';
不考虑 lodash-es 这种库吗？

2023-12-18 14:59 UTC, weatherstar commented on packages/kit-bg/src/endpoints/endpointsMap.ts
> +  base: {
fixed

2023-12-18 14:59 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +    const NAME_RESOLVER = [
fixed

2023-12-18 14:59 UTC, weatherstar commented on packages/kit/src/hooks/useFormOnChangeDebounced.ts
> +import { useEffect, useRef, useState } from 'react';
这里先去掉了，跟 @huhuanming 沟通下把 debounce  增加到 form 组件里去。

2023-12-18 14:59 UTC, weatherstar commented on packages/kit/src/hooks/useFormatData.ts
> +import { useCallback, useMemo } from 'react';
这里是根据历史记录的 timestamp 按照日期进行重新分组，相同日期的放到同一个 section 进行渲染，section title 是根据 locale 的响应式 title。
这里先保持吧，可以挪到后端处理，我跟 @qwang1113 对一下这里需要修改的地方，更新之后我把再把这里统一替换掉。

2023-12-18 14:59 UTC, weatherstar commented on packages/components/src/layouts/Page/PageFooterActions.tsx
> +  onConfirm?: () => void | Promise<boolean> | Promise<void>;
已沟通确认

2023-12-18 14:59 UTC, weatherstar commented on packages/kit-bg/src/endpoints/index.tsx
> +  const settings = await settingsPersistAtom.get();
settingsPersistAtom.get() 是 zuozhuo 封装的方法，里面会 await atom.storageReady 之后再返回

2023-12-18 14:59 UTC, weatherstar commented on packages/kit-bg/src/vaults/base/VaultBase.ts
> +import { isEmpty, isNil } from 'lodash';
目前项目其他地方用的都是 lodash，修改地方较多。要替换的我之后单独提一个 PR 统一替换吧，方便检查。

2023-12-18 15:21 UTC, loatheb requested changes

2023-12-18 15:21 UTC, loatheb commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +          message: 'message__fetching_error',
只要是请求，response 的 message 都会直接根据 request 做好 i18n 返回 message，这里是否不需要这种格式化了

2023-12-18 15:21 UTC, loatheb commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +      }>('/wallet/v1/account/resolve-name', {
这个接口如果在发送流程，to 地址框这里，就建议把地址检测，域名解析等所有流程都放到这个接口里面统一处理，这样的话其他情况不需要处理多个请求

2023-12-18 15:21 UTC, loatheb commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +      endpointType: 'test',
默认值还是用 prod 吧，别以后忘了改了

2023-12-19 01:16 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +      }>('/wallet/v1/account/resolve-name', {
好的，这里我和 @qwang1113 对下接口怎么处理比较好

2023-12-19 01:16 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +          message: 'message__fetching_error',
ok 这里等域名解析/地址检测等接口合并之后统一处理下

2023-12-19 01:16 UTC, weatherstar commented on packages/kit-bg/src/states/jotai/atoms/settings.ts
> +      endpointType: 'test',
fixed

2023-12-19 02:56 UTC, sidmorizon commented on packages/kit-bg/src/vaults/base/VaultBase.ts
> +import { isEmpty, isNil } from 'lodash';
如果要换的话，得用 babel 插件把第三方库用到的 lodash 也换一遍，否则项目里用 lodash-es，第三方库用 lodash，最终输出的包体积可能更大了

2023-12-19 03:15 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +          message: 'message__fetching_error',
fixed

2023-12-19 03:15 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceNameResolver.ts
> +      }>('/wallet/v1/account/resolve-name', {
已沟通

2023-12-19 03:15 UTC, weatherstar commented on packages/kit/src/hooks/useFormatData.ts
> +import { useCallback, useMemo } from 'react';
已沟通

2023-12-19 06:34 UTC, loatheb approved these changes

2023-12-19 06:34 UTC, loatheb commented on packages/kit-bg/src/endpoints/endpointsMap.ts
> +  'test' | 'prod',
对于这里的类型，最好在 store 那块都进行强类型收敛一下

2023-12-19 06:34 UTC, loatheb commented on packages/kit-bg/src/services/ServiceHistory.ts
> +    const onChainHistoryTxs = resp.data.data.data;
这里的 .data 也太多了...

2023-12-19 06:34 UTC, loatheb commented on packages/kit/src/utils/axiosInterceptor.ts
> +  config.headers.set('X-Onekey-Request-Theme', settings.theme);
theme 需要转化为黑色和白色，不要用 auto

2023-12-19 06:34 UTC, loatheb commented on packages/kit/src/utils/axiosInterceptor.ts
> +    platformEnv.distributionChannel,
distributionChannel 的信息不一定全的，类型和渠道可能得重新梳理一下两个字段这里拼接起来

2023-12-19 07:47 UTC, originalix approved these changes

2023-12-19 08:38 UTC, huhuanming approved these changes

2023-12-19 08:40 UTC, merged

2023-12-19 08:48 UTC, sidmorizon commented on packages/kit/src/utils/axiosInterceptor.ts
> +  config.headers.set('X-Onekey-Request-ID', generateUUID());
判断域名白名单，仅限我们内部的服务器增加header，第三方的域名不增加

2023-12-19 08:48 UTC, sidmorizon commented on packages/kit-bg/src/services/ServiceBase.ts
> +  async getClient(endpoint?: string) {
这个 endpoint 是只能用我们自己的服务器么，还是可以传第三方的服务器。

如果是我们自己的，然后希望动态切换，建议传 name ，通过 name 转为 url。

如果允许传第三方的，那么这里就有安全风险，因为  getClient() 默认是使用我们的服务器，所以代码全部会按照我们的服务器来进行接口调用，假如某个开发者不小心 getClient(otherUrl) 修改成了第三方的服务器，就意味着之前的代码逻辑全部会调用到第三方去，导致信息泄露

2023-12-19 08:48 UTC, sidmorizon commented on packages/kit-bg/src/services/ServiceGas.ts
> +        gasPrice: (gasFee.fees[presetIndex] ?? gasFee.fees[0]) as string,
这里不要把普通 gas 和 eip1559 gas 混在一起返回

2023-12-19 08:48 UTC, sidmorizon commented on packages/kit-bg/src/services/ServiceSend.ts
> +  public async buildEncodedTx({
这个不需要了，前端只要 buildUnsignedTx

2023-12-19 08:48 UTC, sidmorizon commented on packages/kit-bg/src/services/ServiceToken.ts
> +    tokens.forEach((token) => {
这个计算让服务器算好了再返回

2023-12-19 08:48 UTC, sidmorizon commented on packages/kit-bg/src/services/ServiceValidator.ts
> +      accountId: "hd-1--m/44'/60'/0'/0/0",
background 里的 networkId 和 accountId 都是从前端传入

2023-12-19 08:48 UTC, sidmorizon commented on packages/kit/src/states/jotai/contexts/token-list/actions.ts
> +  return {
useRef

2023-12-19 13:30 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceValidator.ts
> +      accountId: "hd-1--m/44'/60'/0'/0/0",
这里是做demo用，校验相关内容会挪到服务端去做，这里会接入接口的时统一修改。

2023-12-19 13:31 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceGas.ts
> +        gasPrice: (gasFee.fees[presetIndex] ?? gasFee.fees[0]) as string,
这里让服务端返回的时候提前把 gas eip1559 和  gas 提前拆分出来，目前都是放在 resp.fees 里

2023-12-19 13:31 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceBase.ts
> +  async getClient(endpoint?: string) {
目前是希望做到所有请求都是发给我们自己的服务端