feat: web router is ready to back
OneKeyHQ/app-monorepo pull request #3891
Opened 2023-12-01 08:01 UTC by huhuanming

[Take Me Home, Country Roads](https://www.youtube.com/watch?v=uu7j_xljCRY)

Key Files：
packages/kit/src/routes/config/index.ts
packages/kit/src/routes/config/allowList.ts
packages/kit/src/routes/Tab/TabNavigator.tsx

2023-12-01 12:49 UTC, weatherstar submitted a review, later dismissed

2023-12-05 09:15 UTC, loatheb requested changes

2023-12-05 09:15 UTC, loatheb commented on packages/components/src/layouts/Navigation/Tab/TabBar/DesktopLeftSideBar.tsx
> +        if (platformEnv.isDesktop && route.name === extraConfig?.name) {
这里为什么是桌面端？应该是大屏的时候是这样的吧

2023-12-05 09:18 UTC, huhuanming commented on packages/components/src/layouts/Navigation/Tab/TabBar/DesktopLeftSideBar.tsx
> +        if (platformEnv.isDesktop && route.name === extraConfig?.name) {
现在打开大屏的话，iPad 上可能会显示这个内容。。。

2023-12-05 09:21 UTC, huhuanming commented on packages/components/src/layouts/Navigation/Tab/TabBar/DesktopLeftSideBar.tsx
> +        if (platformEnv.isDesktop && route.name === extraConfig?.name) {
或者我修改成 media.getMd && platformEnv.isDesktop && route.name === extraConfig?.name
这样后续只需要删除 platformEnv.isDesktop 就行

2023-12-05 09:30 UTC, loatheb commented on packages/components/src/layouts/Navigation/Tab/TabBar/DesktopLeftSideBar.tsx
> +        if (platformEnv.isDesktop && route.name === extraConfig?.name) {
那就算了，因为大部分 UI 上的东西，最好都有屏幕来判断，否则以后别的平台迁移很麻烦，需要重新回过头看很多判断 if else 代码

2023-12-05 09:30 UTC, loatheb approved these changes

2023-12-05 09:45 UTC, originalix approved these changes

2023-12-05 11:10 UTC, ezailWang approved these changes

2023-12-05 11:10 UTC, merged