AccountSelector
OneKeyHQ/app-monorepo pull request #3902
Opened 2023-12-05 09:59 UTC by franco-chan

https://github.com/OneKeyHQ/app-monorepo/assets/23469879/b31cdf14-e0da-4225-a4cb-ae361b6b39b5

2023-12-06 01:29 UTC, sidmorizon approved these changes, later dismissed

2023-12-06 01:31 UTC, originalix approved these changes, later dismissed

2023-12-06 02:16 UTC, sidmorizon submitted a review, later dismissed

2023-12-06 06:35 UTC, loatheb approved these changes, later dismissed

2023-12-07 08:24 UTC, sidmorizon submitted a review, later dismissed

2023-12-07 11:16 UTC, originalix submitted a review, later dismissed

2023-12-07 11:17 UTC, revan-zhang requested changes

2023-12-07 11:17 UTC, loatheb commented on packages/components/src/actions/ListItem/index.tsx
> +  const isLocalImage = typeof src === 'number';
这个判断不准确吧

2023-12-07 11:22 UTC, loatheb requested changes

2023-12-07 11:22 UTC, loatheb commented on packages/components/src/actions/Dialog/Content.native.tsx
> +      if (platformEnv.isDev && logContentHeight) {
logContentHeight 和 platfornEnv.isDev 这种属性和参数都能同时出现吗？

2023-12-07 11:28 UTC, huhuanming commented on packages/components/src/actions/Dialog/Content.native.tsx
> +      if (platformEnv.isDev && logContentHeight) {
logContentHeight 用于调试获取组件高度，非生产环境下应该关掉日志。

2023-12-07 11:37 UTC, huhuanming commented on packages/components/src/actions/Dialog/Content.native.tsx
> +      if (platformEnv.isDev && logContentHeight) {
我简化下参数

2023-12-07 12:08 UTC, huhuanming commented on packages/components/src/actions/ListItem/index.tsx
> +  const isLocalImage = typeof src === 'number';
整复杂了，其实可以很简单，分两个参数。
<img width="509" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5743863/0f97da0c-0e72-4c58-85dc-ebeeb547af87">

从参数控制更合理
<img width="532" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5743863/cd2b10b5-4690-473e-93ce-7d12607a1790">

2023-12-07 13:27 UTC, rayston92 commented
かわいい

2023-12-08 01:52 UTC, loatheb approved these changes

2023-12-08 02:28 UTC, originalix approved these changes

2023-12-08 02:48 UTC, sidmorizon approved these changes

2023-12-08 02:48 UTC, merged