Feat/x browser e2e
OneKeyHQ/app-monorepo pull request #3908
Opened 2023-12-06 13:21 UTC by web3rd2

Add testID Props for Discovery Feature in Mobile and Electron e2e Test Cases

2023-12-07 02:08 UTC, sidmorizon commented on packages/components/src/Popover/index.tsx
> +                testID="popover-btn-close"
testID 都加一些随机数作为后缀吧，比如 `testID="popover-btn-close-387263255"`，否则组件多起来，很容易命名冲突。

2023-12-07 03:33 UTC, web3rd2 commented on packages/components/src/Popover/index.tsx
> +                testID="popover-btn-close"
确实，命名冲突以后可能会出现，目前规则如下
 1.testID 都以实例化父组件传入，与父组件名称相关。
 2.一些全局互斥组件直接加再了 基础组件上 为了方便，例如上面Popover。
 3.桌面版和 app相同操作 使用同一testID。
 4.动态组件testID 会与当前组件的 key组合。
 
 后续 实例化父组件处定义 testID 如果没办法避免重复，会考虑下如何添加后缀，以及规则，

2023-12-07 09:26 UTC, huhuanming requested changes

2023-12-07 09:26 UTC, huhuanming commented on packages/components/src/IBaseProps.ts
> +}
可以放到 packages/components/src/type.ts 里面去

2023-12-07 09:33 UTC, huhuanming requested changes

2023-12-07 09:33 UTC, huhuanming commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
>            disabled={displayHomePage || !tab?.canGoBack}
```javascript
const disabled = displayHomePage || !tab?.canGoBack

 accessible={!disabled}
 disabled={disabled}
```

2023-12-07 09:33 UTC, huhuanming commented on packages/kit/src/views/Discovery/components/MobileBrowser/MobileBrowserBottomBar.tsx
> +          accessible={!(displayHomePage ? true : !tab?.canGoForward)}
```javascript
const disabled = displayHomePage ? true : !tab?.canGoForward

 disabled={disabled}
 accessible={!disabled}
```

2023-12-07 10:32 UTC, zyoncode commented on packages/components/src/IBaseProps.ts
> +}
发现没有用了已经 delete

2023-12-07 10:42 UTC, huhuanming approved these changes, later dismissed

2023-12-08 00:56 UTC, originalix commented on packages/kit/src/views/Discovery/components/DesktopCustomTabBarItem/index.tsx
> +                !tab.isBookmark ? 'bookmark' : 'remove bookmark'
`remove-bookmark`

2023-12-08 00:56 UTC, originalix commented on packages/kit/src/views/Discovery/components/HeaderLeftToolBar/index.tsx
> +              !isBookmark ? 'bookmark' : 'remove bookmark'
同上，不要带空格吧

2023-12-08 05:11 UTC, originalix approved these changes

2023-12-08 08:03 UTC, huhuanming approved these changes

2023-12-08 08:23 UTC, sidmorizon approved these changes

2023-12-10 08:19 UTC, loatheb approved these changes

2023-12-10 08:20 UTC, merged