chore: support aysnc import & enabled code split in Metro
OneKeyHQ/app-monorepo pull request #3922
Opened 2023-12-10 08:35 UTC by huhuanming

2023-12-18 02:55 UTC, loatheb requested changes

2023-12-18 02:55 UTC, loatheb commented on apps/mobile/plugins/asyncRequireTpl.js
> +const asyncRequire = require('metro-runtime/src/modules/asyncRequire');
这个写个方案呢？给大家讲一下，这里面原理是什么，是否有安全风险

2023-12-18 03:05 UTC, huhuanming commented on apps/mobile/plugins/asyncRequireTpl.js
> +const asyncRequire = require('metro-runtime/src/modules/asyncRequire');
方案在这里：https://onekeyhq.atlassian.net/wiki/spaces/ONEKEY/pages/405536777/Metro

等 @sidmorizon 回来，我拉个会吧。

2023-12-19 07:12 UTC, huhuanming commented on apps/mobile/plugins/asyncRequireTpl.js
> +const asyncRequire = require('metro-runtime/src/modules/asyncRequire');
沟通了后续节奏：
1. 合并后，在开发模式下用 yarn app:split-bundle 启动，验证开发模式（非默认命令，默认仍然是不分包的命令）;
2. 开发生产环境下的分包加载，验证冷启动时间。 @hellohublot

2023-12-19 10:08 UTC, sidmorizon approved these changes

2023-12-19 13:05 UTC, originalix approved these changes

2023-12-20 02:19 UTC, loatheb approved these changes

2023-12-20 02:19 UTC, merged