feat: add hardware demo hooks
OneKeyHQ/app-monorepo pull request #3966
Opened 2023-12-21 08:11 UTC by huhuanming

2023-12-21 09:24 UTC, loatheb requested changes

2023-12-21 09:24 UTC, loatheb commented on packages/kit/src/hooks/useHardware.tsx
> +  confirmOnClassic: useCallback(confirmOnClassic, []),
封装成 hooks 有什么优势？这里又不涉及到响应式的数据变化，就是单纯的一个 dialog，和直接 import 方法执行会有什么差异？

2023-12-21 10:10 UTC, huhuanming commented on packages/kit/src/hooks/useHardware.tsx
> +  confirmOnClassic: useCallback(confirmOnClassic, []),
挪到组件里去了 😳

2023-12-22 03:38 UTC, loatheb approved these changes

2023-12-22 06:17 UTC, ByteZhang1024 commented on packages/kit/src/components/Hardware/Hardware.tsx
> +export function ConfirmOnClassic() {
为什么要指定 classic，其他设备呢。

2023-12-22 07:36 UTC, huhuanming commented on packages/kit/src/components/Hardware/Hardware.tsx
> +export function ConfirmOnClassic() {
这里是 demo，后续需要开放业务的同学自行修改。。😂 我这里没梳理逻辑的

2023-12-22 08:06 UTC, ezailWang approved these changes

2023-12-22 08:47 UTC, originalix approved these changes

2023-12-22 08:53 UTC, merged