feat: Added bookmark, history, and search logic for discovery page
OneKeyHQ/app-monorepo pull request #3976
Opened 2023-12-22 07:06 UTC by originalix

2023-12-22 09:27 UTC, loatheb requested changes

2023-12-22 09:27 UTC, loatheb commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +import { nanoid } from 'nanoid';
这里为啥要新引入一个 uuid 库

2023-12-22 09:27 UTC, loatheb commented on packages/components/src/actions/ActionList/index.tsx
> +      if (result || result === undefined) {
这段代码刚在另一个 PR 里面有看到过..

2023-12-22 09:27 UTC, loatheb commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +        bookmark[index] = payload;
这种地方其实也可以考虑用 immutable 的写法

```

const bookmarks = [...]
const index = bookmarks.findIndex((item) => item.url === payload.url);

const updatedBookmarks = [
  ...bookmarks.slice(0, index),
  payload,
  ...bookmarks.slice(index + 1),
];
this.buildBookmarkData.call(set, updatedBookmark);

```

好处就是对于 bookmark 是传入进来的引用类型的时候，不会因为引用的连接而修改外部参数，同时尽可能保证着每一个 item 的引用

2023-12-22 09:27 UTC, loatheb commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +    const index = history.findIndex((item) => item.id === payload);
这种代码如果特别多的话，反而不如用 lodash 来写，工具函数处理这些很方便

2023-12-22 09:27 UTC, loatheb commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +            : (isNewWindow || !tabId || tabId === 'home' || maybeDeepLink) &&
我们的发现页还是需要支持 deeplink 吗？这个为了安全起见最好别吧，是有什么场景会遇到

2023-12-22 09:27 UTC, loatheb commented on packages/kit/src/views/Discovery/container/HistoryListModal/index.tsx
> +function formatDate(timestamp: number) {
format 建议统一处理，毕竟也有 i18n 的问题，得和 onekey 客户端的 i18n 一致

2023-12-22 09:27 UTC, loatheb commented on packages/shared/types/discovery.ts
> +  _id: string;
这里服务端接口返回和规则应该都已经改了，后面得同步一下，字段会少很多

2023-12-23 14:53 UTC, originalix commented on packages/components/src/actions/ActionList/index.tsx
> +      if (result || result === undefined) {
huanming 直接在这个分支上改的，后面又抽了个 PR https://github.com/OneKeyHQ/app-monorepo/pull/3974

2023-12-23 14:53 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +import { nanoid } from 'nanoid';
考虑是 nanoid 生成的 id 更短，更轻量，数据量会比 uuid 小

2023-12-23 14:53 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +        bookmark[index] = payload;
之前 Tab 部分不用 immutable 的写法是因为不想新生成数组导致 atom 刷新

书签和历史记录没这个问题，全部改用 immutable 的写法了

2023-12-23 14:53 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +    const index = history.findIndex((item) => item.id === payload);
这里逻辑比较简单，用原生方法和扩展运算符重新简化了一下

2023-12-23 14:53 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +            : (isNewWindow || !tabId || tabId === 'home' || maybeDeepLink) &&
这个 `maybeDeepLink` 是在打开新页面的时候对 url 的一个标记，webview 的 navigation 逻辑中已经拦截了并且会展示对应的 UI

2023-12-23 14:53 UTC, originalix commented on packages/shared/types/discovery.ts
> +  _id: string;
已经对照 API 对 type 进行了精简，后期等后端处理好后会把 _id 字段也换了

2023-12-25 02:56 UTC, loatheb commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +import { nanoid } from 'nanoid';
这里我感觉没有必要的，这两个数据不会差太多的

2023-12-25 03:23 UTC, sidmorizon commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +            : (isNewWindow || !tabId || tabId === 'home' || maybeDeepLink) &&
webview 里的 dapp 通过 walletconnect 连接钱包，dapp 发起交互时，会走 deeplink

2023-12-25 03:29 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +            : (isNewWindow || !tabId || tabId === 'home' || maybeDeepLink) &&
https://github.com/OneKeyHQ/app-monorepo/blob/b91c9b7a02132cbdb3baf44165620cb76f0de567/packages/shared/src/consts/urlProtocolConsts.tsx#L15

WalletConnect 之前也写在支持的列表里，需要这么连的话可以放开

2023-12-25 03:51 UTC, originalix commented on packages/kit/src/states/jotai/contexts/discovery/actions.ts
> +import { nanoid } from 'nanoid';
移除了，统一用 uuid

2023-12-25 03:52 UTC, originalix commented on packages/kit/src/views/Discovery/container/HistoryListModal/index.tsx
> +function formatDate(timestamp: number) {
在 shared 里抽了个 `formatHistoryRecordDate` 格式化函数，相关词条加上了 i18n

看了下 v4 是用 hooks 处理的，感觉没啥必要

2023-12-25 06:35 UTC, loatheb requested changes

2023-12-25 06:35 UTC, loatheb commented on packages/kit/src/views/Discovery/container/SearchModal/index.tsx
> +          _id: SEARCH_ITEM_ID,
这个字段和 i18n 也记得根据接口进行更新

2023-12-25 06:41 UTC, loatheb commented on packages/kit/src/views/Discovery/container/SearchModal/index.tsx
> +    () => Array.isArray(searchList) && searchList.length > 0,
这种 boolean 值可以不用 memo 吧..毕竟 memo 为了防止引用类型数据引用变化？

2023-12-25 07:22 UTC, originalix commented on packages/kit/src/views/Discovery/container/SearchModal/index.tsx
> +          _id: SEARCH_ITEM_ID,
这个插入的 Google 搜索 item 需要单独加个词条，打上 TODO 了

2023-12-25 07:22 UTC, originalix commented on packages/kit/src/views/Discovery/container/SearchModal/index.tsx
> +    () => Array.isArray(searchList) && searchList.length > 0,
嗯，检查了下整个业务的 useMemo 情况，把简单的 boolean 都直接比较了，以免 useMemo 的额外性能损耗

2023-12-26 06:51 UTC, originalix commented on packages/shared/types/discovery.ts
> +  _id: string;
_id 字段也处理了

2023-12-28 02:25 UTC, sidmorizon commented on packages/kit/src/views/Discovery/hooks/useOpenWebsite.ts
> +export function useOpenWebsite({
这个 hooks 放到 useBrowserAction 里统一管理，否则散落在各处很难找到

2023-12-28 02:46 UTC, sidmorizon commented on packages/kit/src/views/Discovery/container/BookmarkListModal/index.tsx
> +      setDataSource((bookmarks as IBrowserBookmark[]) || []);
` const { result } = usePromiseResult` 
usePromiseResult 自带 state，这里不需要自己额外声明。
firstLoad 也可以根据 result 是否为 nil 来判断

2023-12-28 02:46 UTC, sidmorizon commented on packages/kit/src/views/Discovery/container/BookmarkListModal/index.tsx
> +      const bookmarks = await Promise.all(
生成 bookmarks 这个逻辑放到 service 里声明为方法，不要把逻辑写到 UI 层

2023-12-28 02:46 UTC, sidmorizon commented on packages/kit/src/views/Discovery/container/BookmarkListModal/index.tsx
> +  const { buildBookmarkData, removeBrowserBookmark, modifyBrowserBookmark } =
bookmark 这些操作，似乎和 jotai context 无关，因为没有读写 jotai context 的数据，而是直接操作 simple db，那么这些逻辑放到 service 里更适合

2023-12-28 02:46 UTC, sidmorizon commented on packages/kit/src/views/Discovery/container/Dashboard/index.tsx
> +    return data;
如果这个 data 外部不再用到，那么在这里直接拼装 dataSource 后返回，可以节约一个 useMemo 的内存

2023-12-28 02:46 UTC, sidmorizon commented on packages/shared/src/utils/formatDateUtils.ts
> +  const today = dayjs().startOf('day');
通过字符串来判断并不可靠吧，系统环境的多语言和国际化配置不一样，最终输出的文字可能都不相同

2023-12-28 02:46 UTC, sidmorizon commented on packages/shared/src/utils/formatDateUtils.ts
> +  const today = dayjs().startOf('day');
参考 `dayjs().isSame('2011-01-01', 'year')`
https://day.js.org/docs/en/query/is-same

2024-01-16 05:15 UTC, originalix commented on packages/kit/src/views/Discovery/hooks/useOpenWebsite.ts
> +export function useOpenWebsite({
Fixed，写的时候没想到 navigation 可以传到 action 里去

2024-01-16 05:16 UTC, originalix commented on packages/kit/src/views/Discovery/container/BookmarkListModal/index.tsx
> +      setDataSource((bookmarks as IBrowserBookmark[]) || []);
> firstLoad 也可以根据 result 是否为 nil 来判断

已修复

> usePromiseResult 自带 state，这里不需要自己额外声明。

在书签页面，result 还会被外部更改，拖动排序修改源数据。
自查了其他 usePromiseResult 的使用场景，去除了不必要的 useMemo，使用自带的 state

2024-01-16 05:16 UTC, originalix commented on packages/kit/src/views/Discovery/container/BookmarkListModal/index.tsx
> +      const bookmarks = await Promise.all(
Fiexd，书签和历史记录的生成都放入了 service

2024-01-16 05:17 UTC, originalix commented on packages/kit/src/views/Discovery/container/BookmarkListModal/index.tsx
> +  const { buildBookmarkData, removeBrowserBookmark, modifyBrowserBookmark } =
bookmark 跟 jotai context 有关联，添加书签后会同步修改标签页 tab 上的属性

历史记录似乎没关联，但是因为逻辑内聚性还是都放在一起好了，这样代码比较直观

2024-01-16 05:18 UTC, originalix commented on packages/kit/src/views/Discovery/container/Dashboard/index.tsx
> +    return data;
同上，Fixed

2024-01-16 05:19 UTC, originalix commented on packages/shared/src/utils/formatDateUtils.ts
> +  const today = dayjs().startOf('day');
这个不是字符串，是 dayjs 的 start-of 函数，判断时间是否从今天开始

 https://day.js.org/docs/en/manipulate/start-of

2024-01-16 06:22 UTC, sidmorizon approved these changes

2024-01-16 07:59 UTC, weatherstar approved these changes

2024-01-16 09:43 UTC, loatheb approved these changes

2024-01-16 09:46 UTC, merged