Refactor lite card
OneKeyHQ/app-monorepo pull request #3989
Opened 2023-12-25 11:50 UTC by hellohublot

2023-12-25 12:25 UTC, loatheb approved these changes

2023-12-25 12:29 UTC, originalix approved these changes, later dismissed

2023-12-25 12:31 UTC, loatheb requested changes

2023-12-25 12:31 UTC, loatheb commented on yarn.lock
> +    react-native-lite-card: "https://github.com/OneKeyHQ/react-native-lite-card#192f9998009395e5754738089b4b142f8369b206"
这个单独都发成 npm 包吧，就不用 github 链接了

2023-12-25 12:39 UTC, huhuanming commented on yarn.lock
> +    react-native-lite-card: "https://github.com/OneKeyHQ/react-native-lite-card#192f9998009395e5754738089b4b142f8369b206"
用版本号吧

2023-12-25 15:33 UTC, ByteZhang1024 commented on yarn.lock
> +    react-native-lite-card: "https://github.com/OneKeyHQ/react-native-lite-card#192f9998009395e5754738089b4b142f8369b206"
发布成 npm 是不是这个也可以有对外计划？

2023-12-26 06:02 UTC, hellohublot commented on yarn.lock
> +    react-native-lite-card: "https://github.com/OneKeyHQ/react-native-lite-card#192f9998009395e5754738089b4b142f8369b206"
@loatheb 真要发布 npm 吗❤️，因为点发布然后改主库版本其实徒增工作量，而且是相对 pvivate 的仓库，其实不会经常改这些库的哈

2023-12-26 07:01 UTC, loatheb commented on yarn.lock
> +    react-native-lite-card: "https://github.com/OneKeyHQ/react-native-lite-card#192f9998009395e5754738089b4b142f8369b206"
发布吧，因为 github hash 很难 review，改动比较难发现，但是用版本号最起码知道依赖有改动，会 review

2023-12-27 03:04 UTC, huhuanming commented on yarn.lock
> +    react-native-lite-card: "https://github.com/OneKeyHQ/react-native-lite-card#192f9998009395e5754738089b4b142f8369b206"
版本号好一些，回滚也容易一点，hash 不太容易对准版本。。。

2024-01-04 14:56 UTC, originalix approved these changes, later dismissed

2024-01-04 14:56 UTC, originalix commented on apps/mobile/ios/OneKeyWallet/OneKeyWallet.entitlements
> +	</array>
这段缩进不太对

2024-01-04 14:57 UTC, hellohublot commented on yarn.lock
> +    react-native-lite-card: "https://github.com/OneKeyHQ/react-native-lite-card#192f9998009395e5754738089b4b142f8369b206"
Done.

2024-01-04 15:02 UTC, hellohublot commented on apps/mobile/ios/OneKeyWallet/OneKeyWallet.entitlements
> +	</array>
Done.

2024-01-04 15:03 UTC, originalix approved these changes, later dismissed

2024-01-06 10:47 UTC, loatheb approved these changes

2024-01-07 11:20 UTC, originalix approved these changes

2024-01-10 02:21 UTC, sidmorizon approved these changes

2024-01-10 02:24 UTC, merged