fix: fix re-rendering on lazyLoad
OneKeyHQ/app-monorepo pull request #4004
Opened 2023-12-29 09:21 UTC by huhuanming

2024-01-02 01:58 UTC, originalix approved these changes, later dismissed

2024-01-04 02:34 UTC, loatheb requested changes

2024-01-04 02:34 UTC, loatheb commented on packages/components/src/hocs/PageType/index.tsx
> +const map = new Map();
这种基础组建无脑加不会出现性能问题吗？弄个 LRU 最起码能确保不会因为长时间使用出现问题

2024-01-04 03:05 UTC, huhuanming commented on packages/components/src/hocs/PageType/index.tsx
> +const map = new Map();
是这样的，这个高阶函数只用于路由的 Screen 组件上的 Component。
主要是用来声明自己的路由类型，是 modal，还是 stack，还是 fullmodal。
这样外层容器可以根据当前的路由类型更自动化的去处理视图边界与返回操作。
``` jsx
<ModalStack.Screen
    key={key}
    name={name}
    component={PageTypeHOC(key, EPageType.modal, component)}
    // @ts-expect-error
    options={customOptions}
  />
```
component 对应的组件，目前是通过 lazy 加载的，只有页面被访问时才会生效，才会生成一个缓存。
所以 map 的上限是页面数量的上限，目前不会超过 30个。
——————
不加这个会有什么问题呢？
路由动画导致重渲染的时候，由于是高阶函数，每次会生成新的函数签名，那么 Component.type 发生变化就会导致重渲染，所以用 cache 缓存函数签名。

由于是页面组件，上限有限，用 lru 意义不大。
这一块是启动顺序中需要说明的容器层额外去处理的工作，下周会在启动顺序文档中详细更新。

2024-01-05 07:11 UTC, closed without merging