feat: add makeBlockieImageUri to cache the eth blockie base64 image
OneKeyHQ/app-monorepo pull request #4010
Opened 2024-01-04 05:05 UTC by hellohublot

2024-01-04 05:23 UTC, originalix commented on packages/kit/src/views/AccountManagerStacks/AccountSelectorStack/WalletDetails/index.tsx
> +          return value;
其他链怎么处理头像问题？看现在引入的 ethereum-blockies-base64 是只接受 eth address 的传参

2024-01-04 05:39 UTC, huhuanming commented on packages/kit/src/views/AccountManagerStacks/AccountSelectorStack/WalletDetails/index.tsx
> +          return value;
其他链怎么处理头像问题？
——————
可能需要讨论下，这个跟 franco 跟进吗？

2024-01-04 05:52 UTC, originalix commented on packages/kit/src/views/AccountManagerStacks/AccountSelectorStack/WalletDetails/index.tsx
> +          return value;
技术层面调研也可以，需要通用方案，例如任意字符串 (其他链的账户地址) 来生成 blockies 的库

目前用的库看起来不是很通用

2024-01-04 06:03 UTC, hellohublot commented on packages/kit/src/views/AccountManagerStacks/AccountSelectorStack/WalletDetails/index.tsx
> +          return value;
https://snoopy3476.github.io/eth-blockies-rs/ 看起来用的同一个 encode 方法
随便输入一个 0 或者 1，也是有图像生成的哦

2024-01-04 06:06 UTC, originalix commented on packages/kit/src/views/AccountManagerStacks/AccountSelectorStack/WalletDetails/index.tsx
> +          return value;
是同一个项目么？这个 Demo 里有个 ETH-addr 的选项是可以兼容其他链的场景的，但是看起来是个 Rust 项目

2024-01-04 06:12 UTC, huhuanming commented on packages/kit/src/views/AccountManagerStacks/AccountSelectorStack/WalletDetails/index.tsx
> +          return value;
跟 @sidmorizon 确认了，其他链也使用 ethereum-blockies-base64

2024-01-04 06:13 UTC, originalix submitted a review, later dismissed

2024-01-04 06:19 UTC, huhuanming requested changes

2024-01-04 06:19 UTC, huhuanming commented on packages/kit/src/utils/makeBlockieImageUri/index.native.ts
> +
cache 目录可能会被系统清掉。
<img width="638" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5743863/65e5d351-9e2f-4682-b7d2-7d5a9c8d461e">
与 packages/kit/src/views/Discovery/config/Screenshot.constants.ts 一致，在 document 下面加一个 avatar 目录吧。

2024-01-04 07:34 UTC, huhuanming requested changes

2024-01-04 07:34 UTC, huhuanming commented on packages/kit/src/utils/makeBlockieImageUri/index.native.ts
> +
斜杠的话，不要替换为空，替换为空的话，有可能字符串会重，/ 替换为 _。
BASE64 字符串中还有 + 和 =， + 替换为 - 、= 一般替换为 .，我不知道. 会不会影响文件名保存。。。

2024-01-04 07:35 UTC, hellohublot commented on packages/kit/src/utils/makeBlockieImageUri/index.native.ts
> +
@huhuanming  Done.

2024-01-04 07:41 UTC, hellohublot commented on packages/kit/src/utils/makeBlockieImageUri/index.native.ts
> +
@huhuanming Done.

2024-01-05 01:33 UTC, huhuanming requested changes

2024-01-05 01:33 UTC, huhuanming commented on packages/kit/src/utils/makeBlockieImageUri/index.native.ts
> +
这个目录要创建一下，类似：packages/kit/src/views/Discovery/utils/screenshot.ts
<img width="511" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5743863/7168809e-98d3-41e6-90b9-58602ccc2202">

2024-01-05 01:47 UTC, hellohublot commented on packages/kit/src/utils/makeBlockieImageUri/index.native.ts
> +
@huhuanming  是有的哈

https://github.com/OneKeyHQ/app-monorepo/pull/4010/files#diff-9e1011b7c9f7fdf96fe8522b010409f265b4220ef387c1d36d78bbf2b0920c3fR12-R13

2024-01-05 07:47 UTC, huhuanming approved these changes

2024-01-05 07:59 UTC, loatheb approved these changes

2024-01-05 08:33 UTC, originalix approved these changes

2024-01-05 08:33 UTC, merged