feat: add scanQrCode
OneKeyHQ/app-monorepo pull request #4011
Opened 2024-01-04 07:03 UTC by hellohublot

2024-01-04 07:28 UTC, huhuanming requested changes

2024-01-04 07:28 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/utils/index.ts
> +  navigation: NavigationProp<any, any, any, any, any, any>,
navigation 的类型可以标记为
```typescript
navigation:  ReturnType<typeof useAppNavigation>
```

这样的话封装成 hooks 会不会更好一点？😳
```typescript
export const useScanQrCode() {
   const navigation = useAppNavigation()
  ...
 return {
     startScan,
     scanning,
 }
}
```

2024-01-04 07:28 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/router/index.ts
> +    component: ScanQrCodeModal,
用 lazyLoad 加载页面吧。

```typescript
import LazyLoad from '@onekeyhq/shared/src/lazyLoad';

const ScanQrCodeModal = LazyLoad(
  // 需要时 export default 导出
  () => import('../pages/ScanQrCodeModal'),
);
```

2024-01-04 08:19 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/index.ts
> +  navigation: NavigationProp<any, any, any, any, any, any>,
@huhuanming Done

2024-01-04 08:19 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/router/index.ts
> +    component: ScanQrCodeModal,
@huhuanming  Done.

2024-01-04 13:50 UTC, huhuanming approved these changes, later dismissed

2024-01-04 15:08 UTC, originalix commented on packages/components/src/content/ScanQrCode/ScanCamera/index.native.tsx
> +  onScannedCode,
要么加到 skipWords 文件中，或者换一个属性名，`onReadCode`、`handleScanResult` 都行，不然后续调用的时候都有拼写问题

2024-01-04 15:08 UTC, originalix commented on packages/components/src/content/ScanQrCode/ScanCamera/index.native.tsx
> +          onScannedCode?.(event.nativeEvent.codeStringValue);
组件层面可以做一下类型判断，as string 或者 typeof string

2024-01-05 02:16 UTC, hellohublot commented on packages/components/src/content/ScanQrCode/ScanCamera/index.native.tsx
> +          onScannedCode?.(event.nativeEvent.codeStringValue);
@originalix Done.

2024-01-05 02:16 UTC, hellohublot commented on packages/components/src/content/ScanQrCode/ScanCamera/index.native.tsx
> +  onScannedCode,
@originalix Done.

2024-01-05 02:18 UTC, originalix approved these changes

2024-01-05 03:38 UTC, ByteZhang1024 approved these changes

2024-01-05 06:33 UTC, huhuanming approved these changes

2024-01-05 07:44 UTC, merged