chore: proxy all requests with x-proxy header
OneKeyHQ/app-monorepo pull request #4023
Opened 2024-01-09 16:19 UTC by huhuanming

2024-01-10 00:53 UTC, originalix requested changes
```
[HPM] Proxy created: /  -> http://18.138.227.191:9010
[HPM] Subscribed to http-proxy events: [ 'error', 'close' ]
[HPM] GET /utility/v1/discover/dapp/homepage -> http://18.138.227.191:9010
[HPM] Proxy created: /  -> http://18.138.227.191:9010
[HPM] Subscribed to http-proxy events: [ 'error', 'close' ]
[HPM] GET /utility/v1/discover/dapp/homepage -> http://18.138.227.191:9010
[HPM] Proxy created: /  -> http://18.138.227.191:9010
[HPM] Subscribed to http-proxy events: [ 'error', 'close' ]
[HPM] GET /utility/v1/discover/category/list -> http://18.138.227.191:9010
```

功能没问题的，logl evel 等级再提高下，保留 `[HPM] GET /utility/v1/discover/category/list -> http://18.138.227.191:9010` 这样的输出就可以接受了，现在有点密

2024-01-10 02:31 UTC, huhuanming commented
> ```
> [HPM] Proxy created: /  -> http://18.138.227.191:9010
> [HPM] Subscribed to http-proxy events: [ 'error', 'close' ]
> [HPM] GET /utility/v1/discover/dapp/homepage -> http://18.138.227.191:9010
> [HPM] Proxy created: /  -> http://18.138.227.191:9010
> [HPM] Subscribed to http-proxy events: [ 'error', 'close' ]
> [HPM] GET /utility/v1/discover/dapp/homepage -> http://18.138.227.191:9010
> [HPM] Proxy created: /  -> http://18.138.227.191:9010
> [HPM] Subscribed to http-proxy events: [ 'error', 'close' ]
> [HPM] GET /utility/v1/discover/category/list -> http://18.138.227.191:9010
> ```
> 
> 功能没问题的，logl evel 等级再提高下，保留 `[HPM] GET /utility/v1/discover/category/list -> http://18.138.227.191:9010` 这样的输出就可以接受了，现在有点密

我切到 info 试一下

2024-01-10 03:20 UTC, huhuanming commented
> [HPM] GET /utility/v1/discover/category/list -> http://18.138.227.191:9010

<img width="1045" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5743863/77eda0be-909a-4707-b79e-9cc0fe902f85">
修改了下，干脆自己输出 logo 了。
它的 logo，要么很详细，要么就没有。

2024-01-11 01:50 UTC, sidmorizon approved these changes

2024-01-11 02:34 UTC, originalix approved these changes

2024-01-12 06:41 UTC, ezailWang approved these changes

2024-01-12 08:17 UTC, merged