feat: update allow list
OneKeyHQ/app-monorepo pull request #4051
Opened 2024-01-16 16:22 UTC by huhuanming

2024-01-16 16:28 UTC, originalix requested changes

2024-01-16 16:28 UTC, originalix commented on packages/kit/src/routes/config/allowList.ts
> +      },
为啥这些页面需要配置成 showUrl 的，感觉都是一些设置页面、onboarding，有什么特殊的么。

前期感觉除了 4 个 tab 需要配置外，权限都缩到最小，让业务开发者按需添加就好了

2024-01-17 01:13 UTC, huhuanming commented on packages/kit/src/routes/config/allowList.ts
> +      },
showUrl 不会展示参数，只保留链接，😳 所以我这里一次性更新了下主要页面。

onboarding 页面 @sidmorizon zhuozhuo 看看要不要保留 url。
设置页面 @kwoktung ku 看看要不要保留 url。
————
不需要的话，我移除下相关代码。

2024-01-17 01:36 UTC, originalix commented on packages/kit/src/routes/config/allowList.ts
> +      },
全部干掉，有需要的时候他们提 pr，这样也好 review

2024-01-17 03:51 UTC, huhuanming commented on packages/kit/src/routes/config/allowList.ts
> +      },
好嘞

2024-01-17 07:24 UTC, huhuanming commented on packages/kit/src/routes/config/allowList.ts
> +      },
都移除了，只保留首页了。

2024-01-17 07:25 UTC, originalix approved these changes

2024-01-17 09:31 UTC, weatherstar approved these changes

2024-01-17 09:52 UTC, sidmorizon approved these changes

2024-01-18 00:57 UTC, merged