Feat/swap
OneKeyHQ/app-monorepo pull request #4057
Opened 2024-01-17 10:19 UTC by ezailWang

2024-01-24 14:15 UTC, huhuanming commented on packages/kit/src/routes/Modal/router.tsx
> +import { ModalSwapStack } from './SwapModalStack';
SwapModalStack 现在一般是放在 packages/kit/src/views/Swap 中了

2024-01-24 14:16 UTC, huhuanming commented on packages/kit/src/views/Swap/pages/SwapAccountContainer.tsx
> +  const { activeAccount: activeAccount0 } = useActiveAccount({ num: 0 });
0 是什么意思呢？😳

2024-01-26 03:08 UTC, ezailWang commented on packages/kit/src/views/Swap/pages/SwapAccountContainer.tsx
> +  const { activeAccount: activeAccount0 } = useActiveAccount({ num: 0 });
0 就是 swap 的 from 账户..这块逻辑其实还没有定，现在暂时按  from 和 to 来，分别是 0 和 1

2024-02-01 04:05 UTC, sidmorizon commented on packages/kit/src/views/Swap/pages/SwapAccountContainer.tsx
> +  const { activeAccount: activeAccount0 } = useActiveAccount({ num: 0 });
num 是 0 和 1，那是账户选择器不关心实际业务，所以用数字表示。

但是 swap 这里解构出来的命名就没必要用 0 和 1 了啊，直接这样更清楚

```
  const { activeAccount: activeAccountFrom } = useActiveAccount({ num: 0 });
  const { activeAccount: activeAccountTo } = useActiveAccount({ num: 1 });

```

2024-02-05 11:23 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceSwap.ts
> +      if (data.code === 0 && data.data) {
data.code 已经在 axiosInterceptors 里判断过了。其他fetch里的也一起处理下吧

2024-02-05 11:23 UTC, weatherstar commented on packages/kit/src/views/Swap/hooks/useSwapTokens.ts
> +      setSwapNetworks(networks);
这一段逻辑感觉放在 swapNetworksSort 里面封装处理是不是更好一些

2024-02-20 03:38 UTC, huhuanming commented
需要解决下冲突

2024-02-21 03:46 UTC, ezailWang commented on packages/kit/src/views/Swap/hooks/useSwapTokens.ts
> +      setSwapNetworks(networks);
这段逻辑做的事情是，本地有一个网络顺序在 simple 里面，然后这段逻辑是从 db 里面拿出来网络列表，然后跟当前 fetch 的进行 merge ，因为可能出现网络被禁止的情况，或者新的网络出现

2024-02-21 03:48 UTC, ezailWang commented on packages/kit-bg/src/services/ServiceSwap.ts
> +      if (data.code === 0 && data.data) {
1

2024-03-12 13:28 UTC, huhuanming commented on packages/shared/src/config/endpoint.ts
> +    test: 'http://10.44.22.148:7001',
这里测试网络要替换不😳？

2024-03-13 03:03 UTC, ezailWang commented on packages/shared/src/config/endpoint.ts
> +    test: 'http://10.44.22.148:7001',
这个文件没用，我删了

2024-03-14 08:56 UTC, originalix requested changes

2024-03-14 08:56 UTC, originalix commented on packages/kit-bg/src/services/ServiceSwap.ts
> +  async cancelQuoteFetchQuotes() {
```suggestion
  async cancelFetchQute() {
```

2024-03-14 08:56 UTC, originalix commented on packages/kit-bg/src/dbs/simple/entity/simpleDbEntitySwapSlippage.ts
> +  override enableCache = true;
Slippage 配置里如果没必要不需要开启缓存

2024-03-14 08:56 UTC, originalix commented on packages/kit-bg/src/services/ServiceSwap.ts
> +    return [];
```suggestion
      return data?.data ?? []
      Toast.error({ title: 'error', message: data?.message });
    } catch (e) {
      const error = e as { message: string };
      Toast.error({ title: 'error', message: error?.message });
      return []
    }
```
每一层 return 比较直观

2024-03-14 08:56 UTC, originalix commented on packages/kit-bg/src/services/ServiceSwap.ts
> +    const toProvidersArr = toToken.providers.split(',');
ISwapToken.providers 直接用数组类型呢？

```ts
providers: ESwapProviderEnum[]
```

2024-03-14 08:56 UTC, originalix commented on packages/kit-bg/src/services/ServiceSwap.ts
> +  private _quoteCancelSource?: CancelTokenSource;
CancelTokenSource 是一个废弃 API，用新的 AbortController
https://axios-http.com/docs/cancellation

2024-03-14 08:56 UTC, originalix commented on packages/kit-bg/src/services/ServiceSwap.ts
> +      protocol: EExchangeProtocol.SWAP,
EExchangeProtocol 的阅读体验不好，用 `EProtocolOfExchange ` 会更好

2024-03-14 08:56 UTC, originalix commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntitySwapNetworksSort.ts
> +  override enableCache = true;
同上，这里需要缓存在内存中么？

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/components/AccountSelector/AccountSelectorTrigger.tsx
> +export function AccountSelectorTriggerSwap({ num }: { num: number }) {
参考 `packages/kit/src/components/AccountSelector/AccountSelectorTrigger/AccountSelectorTriggerDApp.tsx`

把不同场景的 AccountSelectorTrigger 拆分到单独的文件中

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/components/AccountSelector/AccountSelectorTrigger.tsx
> +  const actions = useAccountSelectorActions();
这部分逻辑可以直接用 useAccountSelectorTrigger 来简化，参考其他文件

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/hooks/useFormatDate.ts
> +};
感觉这个文件中的逻辑都可以在 shared/utils/dateUtils 里找到，能否直接用工具类，不用 hooks

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/hooks/useListenTabFocusState.ts
> +  callback: (isFocus: boolean, isHideByModal: boolean) => void,
isHideByModal 是表示什么场景

@huhuanming 给这个 hooks 写一下注释吧，里面 3 个 find 已经看不懂要干啥了

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/states/jotai/contexts/swap/actions.ts
> +  private approvingInterval: NodeJS.Timeout | undefined;
这里最好使用 ReturnType<typeof setInterval> 来定义类型

https://stackoverflow.com/questions/45802988/typescript-use-correct-version-of-settimeout-node-vs-window

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/components/SwapFromAmountPercentage.tsx
> +const SwapFromAmountPercentage = ({
没有引用的地方，可以移除了

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/components/SwapHistoryTokenInfoItem.tsx
> +const SwapHistoryTokenInfoItem = ({
也搜不到引用

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/components/SwapOnChainInfoItem.tsx
> +const SwapOnChainInfoItem = ({
无引用

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/components/SwapReceiverAddressTypeTrigger.tsx
> +const SwapReceiverAddressTypeTrigger = ({
无引用

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/components/SwapTokenCurrencyValue.tsx
> +const SwapTokenCurrencyValue = ({
无引用

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/components/SwapTxHistoryListCell.tsx
> +    });
```suggestion
    const dateStr = dateUtils.formatDate(new Date(created), {
      hideYear: true,
      onlyTime: item.status !== ESwapTxHistoryStatus.PENDING,
    });
```
看这里的场景应该是用不上 hooks

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/components/SwapTxHistoryStatusItem.tsx
> +const SwapTxHistoryStatusItem = ({
无引用

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/hooks/useSwapTxHistory.ts
> +}
这种历史记录页面的低频场景感觉都不需要定义 Atom
直接在 serviceSwap 里整理好数据，HistoryModal 调用的时候直接取就行

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/hooks/useSwapTxHistory.ts
> +  const internalRef = useRef<Record<string, NodeJS.Timeout>>({});
Timout 类型定义，同上

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/hooks/useSwapTxHistory.ts
> +  );
这段代码这样写嵌套很深，可以优化返回结构。forEach、setInterval 之间没有空隙很难阅读，也可以优化下，类似下面这样



```suggestion
  const triggerSwapPendingHistoryInterval = useCallback(
    debounce(() => {
    if (swapTxHistoryPendingRef.current.length === 0) {
      return;
    }

    swapTxHistoryPendingRef.current.forEach((swapTxHistory) => {
      if (internalRef.current[swapTxHistory.txInfo.txId]) {
        return;
      }

      const interval = setInterval(async () => {
        const txStatusRes = await backgroundApiProxy.serviceSwap.fetchTxState({ 
          // params
        });

        if (txStatusRes.state === ESwapTxHistoryStatus.PENDING) {
          return;
        }

        clearInterval(interval);
        delete internalRef.current[swapTxHistory.txInfo.txId];
        await updateSwapHistoryItem({ 
          // params
        });
      }, 1000 * 5);
      internalRef.current[swapTxHistory.txInfo.txId] = interval;
    });
  }, 100),
    [updateSwapHistoryItem],
  );
```

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/pages/components/SwapHistoryButtonContainer.tsx
> +  const { swapTxHistoryPending } = useSwapTxHistoryStateSyncInterval();
usePremiseResult 从 service 直接查 pending 历史记录的数量，省掉 15 行的 hooks

serviceSwap.getPendingTxCount 这个方法用于 ui 渲染

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/pages/modal/SwapHistoryDetailModal.tsx
> +  }, []);
copy 用 useClipboard

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/pages/modal/SwapHistoryListModal.tsx
> +const SwapHistoryListModal = () => {
同之前，这里实际使用 service 即可满足需求，这样也无需考虑 atom 与 simpledb 的同步问题

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/pages/modal/SwapTokenSelectModal.tsx
> +    </AccountSelectorProviderMirror>
这个 AccountSelectorProviderMirror 能直接放到 withSwapProvider 里么？
看到好几个组件都又手动包了这一层

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/router/types.ts
> +};
参考最新的 x 分支，路由信息挪到 shared 里

2024-03-14 08:56 UTC, originalix commented on packages/kit/src/views/Swap/utils/utils.ts
> +}
这个全局有统一函数的吧

2024-03-14 09:31 UTC, ezailWang commented on packages/kit-bg/src/services/ServiceSwap.ts
> +  async cancelQuoteFetchQuotes() {
1

2024-03-14 09:32 UTC, ezailWang commented on packages/kit-bg/src/dbs/simple/entity/simpleDbEntitySwapSlippage.ts
> +  override enableCache = true;
干掉了，滑点不本地存储了

2024-03-14 09:38 UTC, ezailWang commented on packages/kit-bg/src/services/ServiceSwap.ts
> +    return [];
1

2024-03-14 09:41 UTC, ezailWang commented on packages/kit-bg/src/services/ServiceSwap.ts
> +    const toProvidersArr = toToken.providers.split(',');
前后端统一的数据类型，字符串，后面改 token 接口看下这块优化下

2024-03-14 09:44 UTC, ezailWang commented on packages/kit/src/views/Swap/pages/modal/SwapHistoryDetailModal.tsx
> +  }, []);
1

2024-03-14 10:04 UTC, ezailWang commented on packages/kit/src/views/Swap/pages/modal/SwapTokenSelectModal.tsx
> +    </AccountSelectorProviderMirror>
不一定要用的账户信息

2024-03-14 10:10 UTC, ezailWang commented on packages/kit/src/views/Swap/router/types.ts
> +};
1

2024-03-14 11:24 UTC, originalix commented on packages/kit/src/views/Swap/utils/utils.ts
> +}
accountUtils.shortenAddress

2024-03-14 12:38 UTC, ezailWang commented on packages/kit/src/views/Swap/pages/modal/SwapHistoryListModal.tsx
> +const SwapHistoryListModal = () => {
纪录后续优化

2024-03-15 01:44 UTC, ezailWang commented on packages/kit-bg/src/dbs/simple/entity/SimpleDbEntitySwapNetworksSort.ts
> +  override enableCache = true;
1

2024-03-15 01:44 UTC, ezailWang commented on packages/kit-bg/src/services/ServiceSwap.ts
> +      protocol: EExchangeProtocol.SWAP,
1

2024-03-15 01:49 UTC, ezailWang commented on packages/kit/src/components/AccountSelector/AccountSelectorTrigger.tsx
> +export function AccountSelectorTriggerSwap({ num }: { num: number }) {
1

2024-03-15 01:50 UTC, ezailWang commented on packages/kit/src/hooks/useFormatDate.ts
> +};
需要 local 从 jotai  settings里面取

2024-03-15 01:50 UTC, ezailWang commented on packages/kit/src/hooks/useListenTabFocusState.ts
> +  callback: (isFocus: boolean, isHideByModal: boolean) => void,
是否有 modal 覆盖在上面

2024-03-15 01:51 UTC, ezailWang commented on packages/kit/src/views/Swap/components/SwapFromAmountPercentage.tsx
> +const SwapFromAmountPercentage = ({
1

2024-03-15 01:51 UTC, ezailWang commented on packages/kit/src/views/Swap/components/SwapHistoryTokenInfoItem.tsx
> +const SwapHistoryTokenInfoItem = ({
1

2024-03-15 01:51 UTC, ezailWang commented on packages/kit/src/views/Swap/components/SwapOnChainInfoItem.tsx
> +const SwapOnChainInfoItem = ({
1

2024-03-15 01:51 UTC, ezailWang commented on packages/kit/src/views/Swap/components/SwapReceiverAddressTypeTrigger.tsx
> +const SwapReceiverAddressTypeTrigger = ({
1

2024-03-15 01:52 UTC, ezailWang commented on packages/kit/src/views/Swap/components/SwapTxHistoryListCell.tsx
> +    });
需要用到 local 信息

2024-03-15 01:52 UTC, ezailWang commented on packages/kit/src/views/Swap/components/SwapTxHistoryStatusItem.tsx
> +const SwapTxHistoryStatusItem = ({
1

2024-03-15 02:04 UTC, ezailWang commented on packages/kit/src/components/AccountSelector/AccountSelectorTrigger.tsx
> +  const actions = useAccountSelectorActions();
1

2024-03-15 02:04 UTC, ezailWang commented on packages/kit/src/views/Swap/hooks/useSwapTxHistory.ts
> +}
纪录 后续优化

2024-03-15 02:05 UTC, ezailWang commented on packages/kit/src/views/Swap/hooks/useSwapTxHistory.ts
> +  const internalRef = useRef<Record<string, NodeJS.Timeout>>({});
1

2024-03-15 02:08 UTC, ezailWang commented on packages/kit/src/views/Swap/hooks/useSwapTxHistory.ts
> +  );
1

2024-03-15 02:08 UTC, ezailWang commented on packages/kit/src/views/Swap/pages/components/SwapHistoryButtonContainer.tsx
> +  const { swapTxHistoryPending } = useSwapTxHistoryStateSyncInterval();
纪录 优化

2024-03-15 02:10 UTC, ezailWang commented on packages/kit/src/views/Swap/components/SwapTokenCurrencyValue.tsx
> +const SwapTokenCurrencyValue = ({
1

2024-03-15 02:11 UTC, ezailWang commented on packages/kit/src/states/jotai/contexts/swap/actions.ts
> +  private approvingInterval: NodeJS.Timeout | undefined;
1

2024-03-18 09:22 UTC, originalix approved these changes, later dismissed

2024-03-18 09:27 UTC, originalix approved these changes

2024-03-18 09:33 UTC, huhuanming approved these changes

2024-03-18 09:34 UTC, loatheb approved these changes

2024-03-18 09:36 UTC, merged