feat: add qrcode parse list
OneKeyHQ/app-monorepo pull request #4096
Opened 2024-01-30 03:40 UTC by hellohublot

2024-01-30 08:19 UTC, sidmorizon commented on packages/kit/src/views/Developer/pages/Gallery/Components/stories/ScanQrCode.tsx
>      scanQrCode
用 await 不要用 then

2024-01-30 08:19 UTC, sidmorizon commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/animation.ts
> +export const animation: IQRCodeHandler<IAnimationValue> = (value, options) => {
每种类型给一下示例 value

2024-01-30 08:19 UTC, sidmorizon commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/animation.ts
> +      const animationData = {
指定 TS 类型

2024-01-30 08:19 UTC, sidmorizon commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/index.ts
> +export * from './migrate';
这个排序显式指定，否则容易被 lint 工具给修改

2024-01-30 08:19 UTC, sidmorizon commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +          const itemResult = handler(value, options);
需要两层 try catch，不保证 parse 代码是否有 bug ，导致解析出错，那么要 fallback 两次

- 第一次 fallback 尝试解析为常规 url
- 第二次 fallback 解析为纯文本

2024-01-30 08:19 UTC, sidmorizon commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/animation.ts
> +export const animation: IQRCodeHandler<IAnimationValue> = (value, options) => {
这个协议是干嘛的

2024-01-30 08:19 UTC, sidmorizon commented on tests/unit/parseQRCode.test.ts
> +import useParseQRCode from '@onekeyhq/kit/src/views/ScanQrCode/hooks/useParseQRCode';
单元测试文件和原文件放在一起，否则很难找

2024-01-31 01:07 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/animation.ts
> +export const animation: IQRCodeHandler<IAnimationValue> = (value, options) => {
这个应该是动态二维码的识别

2024-01-31 01:10 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +const handlerList = handlers as Record<string, IQRCodeHandler<IBaseValue>>;
这样制定顺序比较危险。。。

2024-01-31 01:13 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/lightningNetwork.ts
> +export const lightningNetwork: IQRCodeHandler<ILightningNetworkValue> = (
返回值类型需要约束下

2024-01-31 08:07 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/lightningNetwork.ts
> +export const lightningNetwork: IQRCodeHandler<ILightningNetworkValue> = (
@huhuanming   如果指的是 lightningNetwork 这个函数需要约束返回的类型， 这里的 IQRCodeHandler<ILightningNetworkValue> 就相当于 () => ILightningNetworkValue 了

2024-01-31 08:13 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +const handlerList = handlers as Record<string, IQRCodeHandler<IBaseValue>>;
@huhuanming 这里的 handlers 改成随意顺序了，url 和 deeplink 都会在最后面

2024-01-31 08:14 UTC, hellohublot commented on tests/unit/parseQRCode.test.ts
> +import useParseQRCode from '@onekeyhq/kit/src/views/ScanQrCode/hooks/useParseQRCode';
@sidmorizon 已经放过去了，虽然看起来有点怪，可以多了以后可以再挪回来哈

2024-01-31 08:15 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/animation.ts
> +export const animation: IQRCodeHandler<IAnimationValue> = (value, options) => {
@sidmorizon 动态二维码，硬件同事说是用了这个库 https://github.com/ngraveio/bc-ur

2024-01-31 08:17 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +          const itemResult = handler(value, options);
@sidmorizon 这里已经加上了 try catch, 如果都解析失败了，最后面有一个 { type: EQRCodeHandlerType.UNKNOWN, raw: value, data: value }

2024-01-31 08:18 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/index.ts
> +export * from './migrate';
@sidmorizon  这里现在改成随意顺序都可以了

2024-01-31 08:18 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/animation.ts
> +      const animationData = {
@sidmorizon  animationData 的类型已经加上

2024-01-31 08:18 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/animation.ts
> +export const animation: IQRCodeHandler<IAnimationValue> = (value, options) => {
@sidmorizon  每种类型都已经加上示例 value 的注释

2024-01-31 08:18 UTC, hellohublot commented on packages/kit/src/views/Developer/pages/Gallery/Components/stories/ScanQrCode.tsx
>      scanQrCode
@sidmorizon  已经改好了

2024-01-31 12:53 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/ethereum.ts
> +  const urlValue = urlHandler(value, options);
这里每一个 parser 都重新执行了一遍 urlHandler，能否更上一层级处理呢？避免每一次 parser 都要去处理😳

2024-01-31 12:55 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +          Dialog.show({
不显示 showCancelButton，可以使用 Dialog.confirm

2024-01-31 12:56 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +        if (!result) {
forEach 有个问题，即便拿到 result，你也不能 break 出来，建议改成 for loop

2024-01-31 12:58 UTC, huhuanming commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/ethereum.ts
> +  const urlValue = urlHandler(value, options);
可以放在 handlers 之前。

2024-02-01 01:34 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/ethereum.ts
> +  const urlValue = urlHandler(value, options);
@huhuanming 可以了

2024-02-01 01:34 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +          Dialog.show({
@huhuanming 可以了

2024-02-01 01:34 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +        if (!result) {
@huhuanming 可以了

2024-02-01 03:35 UTC, huhuanming approved these changes, later dismissed

2024-02-01 05:52 UTC, originalix requested changes

2024-02-01 05:52 UTC, originalix commented on packages/components/src/content/ScanQrCode/index.tsx
> +import { openSettings } from '@onekeyhq/kit/src/utils/openUrl';
compoents 怎么能从 kit import？

2024-02-01 05:52 UTC, originalix commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/lightningNetwork.ts
> +  if (/^LNURL1/i.test(value)) {
这里 LNURL 是 `LNURL1` 开头的有什么规范文档么？怎么会这么写判断呢

2024-02-01 05:52 UTC, originalix commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/bitcoin.ts
> +      };
就只是这样来解析协议的话，那我们对 BIP-21 的支持也太差了吧，人家从别的比特币钱包 Copy 一个 URL，我们最终只去获取 Address，那别人扫这个二维码的意义是什么呢？

Copy 个地址来转账岂不是更快

2024-02-01 05:52 UTC, originalix commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/ethereum.ts
> +      };
ETH 同理，EIP-681 支持的参数更多

可以先不管 UI 层面要怎么跳转，怎么带参数，我们自己的协议实现一定是要完整的

2024-02-01 05:52 UTC, originalix commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/lightningNetwork.ts
> +  if (/^LNURL1/i.test(value)) {
这里跟上面也一样，不是每个 LNURL 都会有 K1 参数的，起码可以参考下 v4 的解析部分

https://github.com/OneKeyHQ/app-monorepo/blob/c7414b433a142d9806946e3c13e09d8bb4f8c8bc/packages/engine/src/vaults/impl/lightning-network/helper/lnurl.ts#L83

2024-02-01 05:52 UTC, originalix commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.test.ts
> +  });
这里的用例不能是我们又做选手又做裁判，自己写一些简单的用例然后跑通过了没有任何意义。

这里的扫码解析用例是期望能覆盖支持的链对应的 unitest 的

可以参考： https://github.com/bitcoinjs/bip21/blob/master/test/fixtures.json

2024-02-01 07:57 UTC, huhuanming commented on packages/components/src/content/ScanQrCode/index.tsx
> +import { openSettings } from '@onekeyhq/kit/src/utils/openUrl';
如果要从 kit 导入的话，这个组件可以挪到 kit 层

2024-02-05 09:37 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.test.ts
> +  });
@originalix  已经复制了社区实现库的所有用例

2024-02-05 09:38 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/ethereum.ts
> +      };
@originalix  已经改成 EIP-681 为首位支持

2024-02-05 09:38 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/bitcoin.ts
> +      };
@originalix  已经增加字段

2024-02-05 09:38 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCodeHandler/lightningNetwork.ts
> +  if (/^LNURL1/i.test(value)) {
@originalix  已收到以后再加

2024-02-05 09:39 UTC, hellohublot commented on packages/components/src/content/ScanQrCode/index.tsx
> +import { openSettings } from '@onekeyhq/kit/src/utils/openUrl';
@originalix  @huhuamming  已经换了

2024-02-05 11:00 UTC, originalix reviewed
看了下 `ScanQrCode/utils/parseQRCode/handlers/*` 的部分其实都是跟路由无关的解析逻辑，按约定的规范，我们可以考虑抽取 ServiceScanQRCode 来维护这些逻辑，这样 kit 这一层只关注解析的结果和路由跳转、参数填充即可

2024-02-05 11:00 UTC, originalix commented on packages/kit/src/views/ScanQrCode/utils/parseQRCode/handlers/deeplink.ts
> +      ['onekey', 'onekey-wallet'].findIndex(
这里有常量可以用的

2024-02-05 11:00 UTC, originalix commented on packages/kit/src/views/ScanQrCode/utils/parseQRCode/handlers/ethereum.ts
> +  const parseValue = ethParser(value);
每条链的入口特征值控制好，不能把其他链的数据放进来解析

2024-02-05 11:00 UTC, originalix commented on packages/kit/src/views/ScanQrCode/utils/parseQRCode/handlers/walletconnect.ts
> +    if (['wc'].findIndex((item) => item === urlValue.data.urlSchema) !== -1) {
wc 有常量

2024-02-06 02:01 UTC, originalix commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +          const isSingleTokenNetwork = false;
```
const settings = await getVaultSettings({ networkId });
return settings.isSingleToken
```
在其他 PR 里看到有这个设置项，等发送合入后 UI 层可以从 serviceNetwork 里取到这个设置

2024-02-06 03:11 UTC, originalix commented on packages/kit-bg/src/apis/IBackgroundApi.ts
> +  serviceUrlParse: ServiceUrlParse;
看起来里面目前只有一个 parse 解析的方法，感觉 Url 解析这个命名也不够通用，不是所有的 QRCode 都是 URL
不如就叫 ServiceScanQRCode，可以在里面处理一切扫码的业务逻辑，不局限在解析

2024-02-06 05:57 UTC, hellohublot commented on packages/kit-bg/src/apis/IBackgroundApi.ts
> +  serviceUrlParse: ServiceUrlParse;
@originalix 可以了哦

2024-02-06 05:57 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/hooks/useParseQRCode.ts
> +          const isSingleTokenNetwork = false;
@originalix 嗯嗯好的，这里等其他 PR

2024-02-06 05:58 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCode/handlers/walletconnect.ts
> +    if (['wc'].findIndex((item) => item === urlValue.data.urlSchema) !== -1) {
@originalix 已经好了哦

2024-02-06 05:58 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCode/handlers/ethereum.ts
> +  const parseValue = ethParser(value);
@originalix 已经好了哦

2024-02-06 05:58 UTC, hellohublot commented on packages/kit/src/views/ScanQrCode/utils/parseQRCode/handlers/deeplink.ts
> +      ['onekey', 'onekey-wallet'].findIndex(
@originalix 已经好了哦

2024-02-06 08:18 UTC, originalix commented on packages/kit-bg/src/services/ServiceScanQRCode/index.ts
> +    const getNetworkFromImplListAndChainId = memoizee(
- memoizee 需要显式指定 maxAge 过期时间，否则占用内存空间
- 这样写的话每次调用 parse 时都会创建一个新的 memoizee 实例，会按预期生效么？感觉这个函数拆成 service 里的另一个函数就可以

2024-02-06 08:18 UTC, originalix commented on packages/kit/package.json
> +    "eth-url-parser": "^1.0.4",
逻辑挪到 kit-bg 后，对应的库也迁移过去

2024-02-07 01:37 UTC, hellohublot commented on packages/kit-bg/src/services/ServiceScanQRCode/index.ts
> +    const getNetworkFromImplListAndChainId = memoizee(
@originalix 可以了哦

2024-02-07 01:37 UTC, hellohublot commented on packages/kit/package.json
> +    "eth-url-parser": "^1.0.4",
@originalix 可以了哦

2024-02-07 01:51 UTC, originalix commented on packages/kit-bg/src/services/ServiceScanQRCode/index.ts
> +        ),
这里感觉把 backgorundApi 传进去更好扩展一点

```ts
return parseQRCode(value, {
      ...options,
      backgroundApi: this.backgroundApi
})
```

就像 ServiceScanQRCode 的构造函数，这样解析函数内部就可以用 service 的各种能力了

```ts
network: await options?.getNetwork?.([IMPL_BTC], '0'),
```

否则像 BTC 里👆🏻的这种代码就读的比较怪，chainId 直接被硬编码了，BTC 不是很关注 chainId，直接通过 networkId 取就可以，比如这样👇🏻

```ts
serviceNetwork.getNetwork({ networkId: getNetworkIdsMap().btc })
```

2024-02-07 01:51 UTC, originalix commented on packages/kit-bg/src/services/ServiceScanQRCode/utils/parseQRCode/handlers/ethereum.ts
> +    const network = await options?.getNetwork?.([IMPL_EVM], chainId);
如果按上面改的话，这里就这样处理，也很清晰了
serviceNetwork 里也无需新增一个新函数

```ts
const { networks } = backgroundApi.serviceNetwork.getNetworksByImpls({impls: [IMPL_EVM]})
const network = networks.find(n => n.chainId === chainId)
```

2024-02-07 07:32 UTC, hellohublot commented on packages/kit-bg/src/services/ServiceScanQRCode/index.ts
> +        ),
@originalix 可以了哦

2024-02-07 07:32 UTC, hellohublot commented on packages/kit-bg/src/services/ServiceScanQRCode/utils/parseQRCode/handlers/ethereum.ts
> +    const network = await options?.getNetwork?.([IMPL_EVM], chainId);
@originalix 可以了哦

2024-02-07 07:41 UTC, originalix approved these changes, later dismissed

2024-02-19 05:49 UTC, originalix commented
处理下冲突吧

2024-02-19 11:44 UTC, hellohublot commented
> 处理下冲突吧

@originalix 可以了

2024-02-19 11:55 UTC, originalix approved these changes, later dismissed

2024-02-20 04:08 UTC, sidmorizon approved these changes

2024-02-20 04:09 UTC, originalix approved these changes

2024-02-20 05:53 UTC, huhuanming approved these changes

2024-02-20 05:53 UTC, merged