feat: hardware sign
OneKeyHQ/app-monorepo pull request #4129
Opened 2024-02-18 08:45 UTC by sidmorizon

2024-02-19 01:12 UTC, originalix commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +          }
固件验真的标记写入数据库的话就还需要考虑固件版本变化的场景，之后连接的固件版本不一致，是否需要更新这个标记

不然出厂固件没问题，后面升级了一个被 hack 的固件，但是钱包这里还是显示固件验真成功的标记

2024-02-19 01:12 UTC, originalix commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +    let id = `${networkId}--${address}`;
像闪电网络这种无地址的网络，可能只需要匹配 lightningAddress 是不是某个钱包账户的地址，是不是只能在外部魔改传入的 account 的参数了

```
{
  address: '',
  addresses: {
    hashAddress: 'xxxxx',
    lightningAddress: 'leon@onekey.so'
  }
}
```

2024-02-19 01:12 UTC, originalix commented on packages/kit/src/states/jotai/contexts/accountSelector/actions.ts
> +import { wait } from '@onekeyfe/hd-core';
这个 import 感觉是不符合预期的...

2024-02-19 02:29 UTC, sidmorizon commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +          }
确实，这里再加上版本号的校验

2024-02-19 02:30 UTC, sidmorizon commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +    let id = `${networkId}--${address}`;
直接将 lightningAddress 写入 address？

2024-02-19 02:37 UTC, originalix commented on packages/kit-bg/src/dbs/local/LocalDbBase.ts
> +    let id = `${networkId}--${address}`;
这个接链的时候再评估下吧，代码里有很多 `if (account.address)` 的场景，不确定直接写进去会不会有其他影响

另外这种场景得抽个方法出来，像闪电网络这类场景就不读 address 字段了，可能会去读 addresses.hashAddress 字段

2024-02-19 07:57 UTC, sidmorizon commented on packages/kit/src/states/jotai/contexts/accountSelector/actions.ts
> +import { wait } from '@onekeyfe/hd-core';
fixed

2024-02-19 08:01 UTC, originalix approved these changes

2024-02-19 13:20 UTC, ByteZhang1024 approved these changes, later dismissed

2024-02-20 00:19 UTC, originalix requested changes
```if (isFirmwareVerified) {
  const versionText = deviceUtils.getDeviceVersionStr(device);
  item.verifiedAtVersion = versionText;
}```

辛苦把 verifiedAtVersion 的逻辑去掉吧

2024-02-20 01:03 UTC, sidmorizon commented
> ```
>   const versionText = deviceUtils.getDeviceVersionStr(device);
>   item.verifiedAtVersion = versionText;
> }```
> 
> 辛苦把 verifiedAtVersion 的逻辑去掉吧
> ```

为什么要去掉

2024-02-20 01:59 UTC, originalix approved these changes

2024-02-20 02:48 UTC, weatherstar approved these changes

2024-02-20 04:55 UTC, ByteZhang1024 approved these changes

2024-02-20 04:55 UTC, merged