feat: btc vault
OneKeyHQ/app-monorepo pull request #4169
Opened 2024-03-03 15:12 UTC by weatherstar

2024-03-04 07:15 UTC, sidmorizon approved these changes

2024-03-04 07:17 UTC, sidmorizon approved these changes, later dismissed

2024-03-04 11:59 UTC, originalix approved these changes

2024-03-04 12:00 UTC, originalix requested changes

2024-03-04 12:00 UTC, originalix commented on packages/core/package.json
> +    "coinselect": "https://github.com/OneKeyHQ/coinselect.git#91e8db20cf3464143cb9d404dee6de7fabb3b04a",
发 npm 包吧

2024-03-07 02:09 UTC, originalix approved these changes

2024-03-07 02:09 UTC, originalix commented on packages/core/package.json
> +    "coinselect": "https://github.com/OneKeyHQ/coinselect.git#91e8db20cf3464143cb9d404dee6de7fabb3b04a",
TODO: 另发 PR 替换

2024-03-07 02:40 UTC, huhuanming approved these changes

2024-03-07 06:22 UTC, kwoktung approved these changes

2024-03-07 06:22 UTC, merged