styles: setting page styles
OneKeyHQ/app-monorepo pull request #4174
Opened 2024-03-05 06:39 UTC by kwoktung

2024-03-06 04:02 UTC, loatheb approved these changes, later dismissed

2024-03-06 10:33 UTC, huhuanming commented
可以 review 了吗？

2024-03-07 01:11 UTC, huhuanming submitted a review, later dismissed

2024-03-07 01:53 UTC, sidmorizon commented on packages/kit/src/views/Setting/pages/AccountDerivation/index.tsx
> +          sceneName: EAccountSelectorSceneName.home,
首页切换到 ETH 链，这里的 0 是不是变成了 ETH 的派生，而不是 BTC 的派生。

如果是的话，用一个新的 name，避免被首页的数据影响
EAccountSelectorSceneName.settingsDeriveType

2024-03-07 01:53 UTC, sidmorizon commented on packages/kit/src/views/Setting/pages/AccountDerivation/index.tsx
> +      backgroundApiProxy.serviceNetwork.getNetworkIdsByImpls({
getAllNetworkIds

2024-03-07 01:53 UTC, sidmorizon commented on packages/kit/src/views/Setting/pages/AccountDerivation/index.tsx
> +          0: {
开发环境把 tbtc 加上，测试链可以从 num 10000 开始，避免冲突

2024-03-07 01:53 UTC, sidmorizon commented on packages/kit/src/views/Setting/pages/AccountDerivation/index.tsx
> +        enabledNum={[0, 1]}
把配置集中管理，然后生成 enabledNum、availableNetworksMap、和 AccountDerivationListItem，否则很容易造成三个配置不同步

2024-03-07 01:53 UTC, sidmorizon commented on packages/kit/src/views/Setting/pages/AccountDerivation/index.tsx
> +        enabledNum={[0, 1]}
```
const configs   =  {
     0: { num: 0, networkIds, defaultNetworkId, title, icon },
}
const { enabledNum, items,  availableNetworksMap } = useMemo(()=>{
     const enabledNum = Object.keys(configs)
     const items = Object.values(configs)
     const availableNetworksMap = configs;
     return { enabledNum, items,  availableNetworksMap }
}, [configs])
```

2024-03-07 02:38 UTC, originalix requested changes

2024-03-07 02:38 UTC, originalix commented on packages/kit/src/views/Setting/pages/AccountDerivation/index.tsx
> +          sceneName: EAccountSelectorSceneName.home,
如用 EAccountSelectorSceneName.settingsDeriveType 来存派生类型的话，AccountSelector buildAccount 的时候也得联动的修改取全局派生方式的逻辑...

2024-03-07 02:38 UTC, originalix commented on packages/kit/src/views/Setting/pages/List/ResourceSection/index.tsx
> +        url="https://help.onekey.so/hc/en-us/requests/new"
useHelpLink 里直接硬编码了一次 `https://help.onekey.so/hc`

这里的 URL 又一次 `https://help.onekey.so/hc/en-us/requests/new`，并且还把语言设置成了 en-us，没有 i18n 考虑

以及之前 HardwareSDK 那边的

```
const onPressBridgeStatus = useCallback(() => {
    openUrlExternal('http://127.0.0.1:21320/status/');
  }, []);
```

这些都是可以放到 packages/shared/src/config/appConfig.ts 里的呀，这样用到哪些外链心里也有数

2024-03-07 02:38 UTC, originalix commented on packages/kit/src/views/Setting/pages/List/SecuritySection/CleanDataItem/index.tsx
> +  ]);
这里用 key-value 的枚举来表示

这种代码维护起来很麻烦啊，如果产品设计要求 `Token & NFT Data` 之前再增加一个新的设置项，那你从上到下又要改一遍对应的 index

```ts
value={val[2]}
onChange={(value) => onChange(value as boolean, 2)}
```

2024-03-07 04:33 UTC, sidmorizon commented on packages/kit/src/views/Setting/pages/AccountDerivation/index.tsx
> +          sceneName: EAccountSelectorSceneName.home,
现在默认都是全局联动，不全局联动的功能还没加

2024-03-07 10:05 UTC, huhuanming submitted a review, later dismissed

2024-03-08 01:22 UTC, originalix commented on packages/kit-bg/src/services/ServiceSetting.ts
> +        icon: 'https://onekey-asset.com/assets/btc/btc.png',
这里的 icon 都读 network 配置，拿 logoURI

2024-03-08 02:38 UTC, originalix approved these changes

2024-03-08 02:55 UTC, sidmorizon approved these changes

2024-03-08 03:32 UTC, huhuanming approved these changes

2024-03-08 03:33 UTC, merged