fix: fix the issue where the ext cannot start running & set v3 ext in default.
OneKeyHQ/app-monorepo pull request #4205
Opened 2024-03-08 14:51 UTC by huhuanming

2024-03-08 15:22 UTC, loatheb submitted a review, later dismissed

2024-03-08 15:32 UTC, originalix approved these changes

2024-03-08 15:37 UTC, originalix requested changes
![CleanShot 2024-03-08 at 23 34 49@2x](https://github.com/OneKeyHQ/app-monorepo/assets/16911056/a46c1117-de6a-45be-b2bf-5e63756326d4)

还是有这个问题

2024-03-08 16:47 UTC, originalix approved these changes

2024-03-09 01:01 UTC, sidmorizon approved these changes

2024-03-09 08:52 UTC, loatheb approved these changes

2024-03-09 08:52 UTC, merged