feat: <AddressInput /> support first transfer API
OneKeyHQ/app-monorepo pull request #4217
Opened 2024-03-11 11:02 UTC by kwoktung

2024-03-12 05:17 UTC, originalix submitted a review, later dismissed

2024-03-12 08:48 UTC, revan-zhang requested changes

2024-03-12 08:48 UTC, revan-zhang commented on packages/kit-bg/src/services/ServiceAccountProfile.ts
> +      return false;
错误了直接 false 是什么操作？产品层面最起码区分清楚是请求失败了我们会提示 warning 这种，直接就判断不是第一次转账太草率了

2024-03-13 02:02 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceAccountProfile.ts
> +      return false;
可以跟产品对下，接口无数据或者错误提示未确认，类似DApp风险检测的处理

2024-03-14 06:58 UTC, kwoktung commented on packages/kit-bg/src/services/ServiceAccountProfile.ts
> +      return false;
改了， 添加了一个 未确认 的状态

2024-03-14 12:20 UTC, huhuanming approved these changes

2024-03-15 01:00 UTC, originalix approved these changes

2024-03-15 06:46 UTC, weatherstar approved these changes

2024-03-15 06:49 UTC, loatheb approved these changes

2024-03-15 06:49 UTC, merged