fix: swap import account select bug
OneKeyHQ/app-monorepo pull request #4345
Opened 2024-03-26 07:28 UTC by ezailWang

2024-03-26 07:49 UTC, huhuanming requested changes

2024-03-26 07:49 UTC, huhuanming commented on packages/shared/src/utils/accountSelectorUtils.ts
> +      // result.deriveType = mergedByData.deriveType;
这个是为什么暂时注释掉呢 😳，需要添加下注释吗？以后会恢复吗？

2024-03-26 09:58 UTC, ezailWang commented on packages/shared/src/utils/accountSelectorUtils.ts
> +      // result.deriveType = mergedByData.deriveType;
我加下注释

2024-03-26 13:30 UTC, huhuanming approved these changes, later dismissed

2024-03-27 01:56 UTC, huhuanming approved these changes

2024-03-27 01:58 UTC, originalix approved these changes

2024-03-27 02:04 UTC, sidmorizon approved these changes

2024-03-27 02:04 UTC, merged