Fix v4: pro nft width and height OK-26645
OneKeyHQ/app-monorepo pull request #4484
Opened 2024-04-23 01:44 UTC by ByteZhang1024

2024-04-23 01:57 UTC, huhuanming commented
lint 挂了。。

2024-04-23 01:58 UTC, originalix requested changes
除了 NFT，还有 HomeScreen 的地方也要看下缩略图要不要变

以及李琰提到了 Pro 的图片裁切的时候需要增加圆角，也需要看下图片库支持么

2024-04-23 02:25 UTC, ByteZhang1024 commented
> 除了 NFT，还有 HomeScreen 的地方也要看下缩略图要不要变
> 
> 以及李琰提到了 Pro 的图片裁切的时候需要增加圆角，也需要看下图片库支持么

V4 不支持设置 Pro 的 HomeScreen。
圆角我看现有的库不支持，就没找新的库，不打算在 V4 上支持了。

2024-04-23 05:54 UTC, originalix approved these changes

2024-04-23 05:55 UTC, originalix commented
> V4 不支持设置 Pro 的 HomeScreen。
> 圆角我看现有的库不支持，就没找新的库，不打算在 V4 上支持了。

@huhuanming v5 上 Touch、Pro 的壁纸、NFT 图片处理，可以提前调研下图片裁切的圆角怎么支持

2024-04-25 01:43 UTC, huhuanming approved these changes

2024-04-25 01:48 UTC, sidmorizon approved these changes

2024-04-25 01:56 UTC, merged