feat: Add support for private BTC external account connection
OneKeyHQ/app-monorepo pull request #4488
Opened 2024-04-23 09:25 UTC by originalix

2024-04-25 04:41 UTC, huhuanming commented
@SocketSecurity ignore npm/protobufjs@6.11.4
@SocketSecurity ignore npm/esbuild@0.19.12

2024-04-25 04:41 UTC, huhuanming submitted a review, later dismissed

2024-04-26 01:16 UTC, weatherstar submitted a review, later dismissed

2024-04-26 06:21 UTC, kwoktung submitted a review, later dismissed

2024-04-29 23:14 UTC, sidmorizon requested changes

2024-04-29 23:14 UTC, sidmorizon commented on packages/kit-bg/src/providers/backgroundProviders.ts
> +    [IInjectedProviderNames.$privateExternalAccount]:
新搞一个 ProviderApi 默认是开放式的，不是命名成 private 就不允许其他网站调用了。

ProviderApiPrivate 限制其他网站调用，仅允许 OneKey 自己的网站调用，参考
BackgroundApiBase.handleProviderMethods

2024-04-29 23:14 UTC, sidmorizon commented on packages/kit-bg/src/providers/backgroundProviders.ts
> +    [IInjectedProviderNames.$privateExternalAccount]:
可以尝试把域名限制写成 decrator 挂载在 class 的声明上，这样会更直观点

2024-04-30 02:20 UTC, originalix commented on packages/kit-bg/src/providers/backgroundProviders.ts
> +    [IInjectedProviderNames.$privateExternalAccount]:
确实，想起来有个限制域名的逻辑了，这里晚点处理下

2024-05-26 04:05 UTC, originalix commented on packages/kit-bg/src/providers/backgroundProviders.ts
> +    [IInjectedProviderNames.$privateExternalAccount]:
Fixed

2024-05-27 08:15 UTC, weatherstar approved these changes, later dismissed

2024-05-28 01:37 UTC, sidmorizon approved these changes

2024-05-28 01:45 UTC, huhuanming approved these changes

2024-05-28 01:45 UTC, merged