feat: add market list
OneKeyHQ/app-monorepo pull request #4623
Opened 2024-05-22 01:23 UTC by huhuanming

<img width="1152" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5743863/66f5e7b5-6148-4dbf-bebf-f79391e5d029">

<img width="1429" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5743863/cd814c82-f9b3-4f38-a11c-edc5b705da37">

2024-05-22 14:45 UTC, huhuanming commented
@SocketSecurity ignore npm/esbuild@0.15.18
@SocketSecurity ignore npm/secp256k1@3.8.0
@SocketSecurity ignore npm/keccak@1.4.0
@SocketSecurity ignore npm/electron@27.0.0
@SocketSecurity ignore npm/realm@12.3.0

2024-05-24 02:11 UTC, originalix requested changes

2024-05-24 02:11 UTC, originalix commented on packages/kit-bg/src/services/ServiceMarket.ts
> +    if (code !== 0) {
`data.code !== 0` 会被 interceptor 拦截抛错吧

2024-05-24 02:11 UTC, originalix commented on packages/kit-bg/src/services/ServiceMarket.ts
> +    if (code !== 0) {
https://github.com/OneKeyHQ/app-monorepo/blob/a6f1502f5efcde4e8f3d6f198668b30832fd662b/packages/shared/src/request/axiosInterceptor.ts#L42

2024-05-24 02:11 UTC, originalix commented on packages/kit-bg/src/services/ServiceMarket.ts
> +    return code === 0 ? data : [];
同上，code = 0 的判断问题

2024-05-24 02:11 UTC, originalix commented on packages/kit-bg/src/services/ServiceMarket.ts
> +    if (code === 0) {
同上

2024-05-24 02:11 UTC, originalix commented on packages/kit-bg/src/states/jotai/atoms/marketWatchList.ts
> +});
业务层不应该使用全局 atom 管理状态

参考 `kit/src/state` 底下各业务线的处理，因为这些 atom 只有当用户在使用 Market 时才需要创建

数据流应该是 `action -> serviceMarket.fetchXXX -> Update Market Atom`

大部分场景也不需要上述的数据流，如果对 UI 响应式有更新的话可以使用上面👆🏻 的方式；

如果仅仅是需要利用全局 Atom 来持久化数据的，那么 `serviceMarket + simpleDb + usePromiseResult` 可能就满足需求了

2024-05-24 02:11 UTC, originalix commented on packages/kit-bg/src/states/jotai/atoms/universalSearch.ts
> +});
同理，这个也是，最近搜索记录存 simpleDb 能解决问题么

全局状态里最好只保存单纯的状态，不跟数据挂钩

2024-05-24 14:48 UTC, originalix approved these changes

2024-05-27 02:57 UTC, ezailWang approved these changes

2024-05-27 02:57 UTC, merged