feat: support algo, ckb data & fix several issues OK-27484 OK-27478
OneKeyHQ/app-monorepo pull request #4633
Opened 2024-05-24 06:26 UTC by weatherstar

2024-05-24 06:42 UTC, originalix requested changes

2024-05-24 06:42 UTC, originalix commented on packages/core/src/chains/ckb/CoreChainSoftware.ts
> +    });
client 和 backgroundApiProxy 分别从 kit-bg 和 kit 引用，这样是不可以的

core 是最底层，不能在这里进行网络请求，数据应该在外部加工好传入

2024-05-24 06:42 UTC, originalix commented on packages/core/src/chains/ckb/CoreChainSoftware.ts
> +    });
txSkeleton 数据可以在签名前，放到 keyring 中处理好

2024-05-24 06:42 UTC, originalix commented on packages/core/src/chains/ckb/CoreChainSoftware.ts
> +    });
https://github.com/OneKeyHQ/app-monorepo/blob/67c037345926eb995afa7e967bb1c6a684d371fc/packages/kit-bg/src/vaults/impls/sui/KeyringHd.ts#L45 参考这里

2024-05-26 08:47 UTC, weatherstar commented on packages/core/src/chains/ckb/CoreChainSoftware.ts
> +    });
fixed

2024-05-26 13:40 UTC, originalix commented on packages/core/src/chains/ckb/CoreChainSoftware.ts
>  import { getConfig } from '@onekeyhq/kit-bg/src/vaults/impls/ckb/utils/config';
把这两个函数都挪到 core 的 sdk 中，kit-bg 从 core 引用

2024-05-27 00:56 UTC, weatherstar commented on packages/core/src/chains/ckb/CoreChainSoftware.ts
>  import { getConfig } from '@onekeyhq/kit-bg/src/vaults/impls/ckb/utils/config';
fixed

2024-05-27 00:58 UTC, originalix approved these changes

2024-05-27 03:20 UTC, huhuanming approved these changes

2024-05-27 03:23 UTC, merged