fix: Polkadot
OneKeyHQ/app-monorepo pull request #4635
Opened 2024-05-24 11:03 UTC by huanxiangspace

2024-05-25 00:17 UTC, originalix requested changes

2024-05-25 00:17 UTC, originalix commented on package.json
> +    "@polkadot/util-crypto": "^12.6.1",
要降版本就把版本固定吧

2024-05-25 00:17 UTC, originalix commented on packages/kit-bg/src/services/ServiceToken.ts
> +    return vaultSettings.nativeTokenAddress;
nativeTokenAddress 配置在 networkInfo 里后，这个原先的配置项就移除吧

在 VaultSettings 的类型里也处理下，最终返回空字符串就行

2024-05-28 00:41 UTC, originalix submitted a review, later dismissed

2024-05-28 02:48 UTC, originalix commented
处理下冲突呢

2024-05-28 03:18 UTC, originalix approved these changes, later dismissed

2024-05-28 05:51 UTC, originalix commented
看下 lint 问题

2024-05-28 10:52 UTC, originalix approved these changes, later dismissed

2024-05-29 02:08 UTC, originalix approved these changes

2024-05-29 04:06 UTC, weatherstar approved these changes

2024-05-29 04:06 UTC, merged