fix issues: OK-28542 OK-28511 OK-28510 OK-28505 OK-28504 OK-28084
OneKeyHQ/app-monorepo pull request #4718
Opened 2024-06-10 15:49 UTC by weatherstar

2024-06-10 15:54 UTC, originalix requested changes

2024-06-10 15:54 UTC, originalix commented on packages/kit-bg/src/services/ServiceAccount/ServiceAccount.ts
> +            ? (account as IDBVariantAccount).addresses[networkId]
感觉这里是不对的，一般来说 db.addresses 里只存储了 prepareAccount 时保存的数据，而对于包含子链的链，地址是通过 vault.buildAddressDetails 在 runtime 计算出来的，例如 cosmos

2024-06-10 15:56 UTC, originalix commented on packages/kit-bg/src/vaults/base/KeyringWatchingBase.ts
> +      addresses: { [this.networkId]: normalizedAddress },
例如这里，子链信息并不会再次更新进 addresses 中了，addresses 里只有一个网络的数据

2024-06-10 16:11 UTC, weatherstar commented on packages/kit-bg/src/services/ServiceAccount/ServiceAccount.ts
> +            ? (account as IDBVariantAccount).addresses[networkId]
fixed

2024-06-10 16:14 UTC, originalix approved these changes, later dismissed

2024-06-11 02:00 UTC, huhuanming approved these changes

2024-06-11 02:31 UTC, originalix approved these changes

2024-06-11 02:31 UTC, merged