fix: video NFT
OneKeyHQ/app-monorepo pull request #4726
Opened 2024-06-11 10:35 UTC by huanxiangspace

2024-06-11 15:26 UTC, originalix requested changes

2024-06-11 15:26 UTC, originalix commented on packages/components/src/primitives/Image/ImageNet.tsx
> +  const video = document.createElement('video');
Native 端没法这么创建 video 元素

2024-06-11 15:26 UTC, originalix commented on packages/components/src/primitives/Image/ImageNet.tsx
> +  const video = document.createElement('video');
看看 expo 有没有什么库来解决，v4 是这么处理 video 的么？

2024-06-12 02:05 UTC, huhuanming commented on packages/components/src/primitives/Image/ImageNet.tsx
> +  const video = document.createElement('video');
可以用 video 组件 （packages/components/src/content/Video），各个端都能跑

2024-06-12 02:08 UTC, huhuanming commented
视频的话，得用 video 组件 😳

2024-06-12 03:07 UTC, huanxiangspace commented
这种try video、try image的方式太粗暴了，后续还是得改成根据Content Type来判断比较靠谱

2024-06-12 04:18 UTC, huhuanming commented
![6062dccc2aaa](https://github.com/OneKeyHQ/app-monorepo/assets/5743863/635c8e81-047a-4103-b582-725544e339f1)

2024-06-12 05:48 UTC, originalix submitted a review, later dismissed

2024-06-12 05:48 UTC, originalix commented
lint 看下

2024-06-12 08:31 UTC, huhuanming commented on packages/components/src/primitives/Image/hooks.tsx
> +      return Video as unknown as ReturnType<IUseImageComponent>;
image 组件中包含了 video 组件。。。有点怪怪的

2024-06-12 08:34 UTC, huhuanming commented on packages/kit/src/components/NFT/NFTDetails/CommonAsset/CommonAssetImage.tsx
> +        <Image.Source src={nft.metadata?.image} controls />
Image.Source 上有 controls，感觉语义不太合理。

我理解应该在这里通过 type 区分是图片还是 video，而不是在 image 里面区分是图片还是 video 并在 Image 内部判断是否加载 video 组件。

2024-06-12 09:11 UTC, huanxiangspace commented on packages/kit/src/components/NFT/NFTDetails/CommonAsset/CommonAssetImage.tsx
> +        <Image.Source src={nft.metadata?.image} controls />
是的，这就是个临时方案，处处充斥着难受，我再改改，先判断

2024-06-13 08:14 UTC, originalix approved these changes

2024-06-13 08:16 UTC, huhuanming approved these changes

2024-06-13 08:16 UTC, merged