OK-28628 OK-28754 OK-28752 OK-28618: fix address input resolve name error
OneKeyHQ/app-monorepo pull request #4745
Opened 2024-06-12 14:21 UTC by kwoktung

2024-06-12 14:27 UTC, originalix approved these changes

2024-06-12 14:42 UTC, originalix requested changes

2024-06-12 14:42 UTC, originalix commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
地址簿是否支持，在 vault.settings 里加设置项

导入私钥、导入观察账户同理，读取已有设置项

2024-06-12 15:22 UTC, kwoktung commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
网络选择器 UI 和 vault 绑起来吗？

2024-06-12 15:23 UTC, originalix commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
这里是地址簿的业务逻辑的一部分吧

2024-06-12 15:29 UTC, originalix commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
都声明到 serviceNetwork 里呢？

getAddressBookExcludeNetworks
getImportedAccountExcludeNetworks

2024-06-12 15:30 UTC, kwoktung commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
这里理论上是 excludedNetworkIds 给 单纯的UI组件 ChainSelector 参数。理论上专注 networkId 处理。用来控制 UI的展示的。

2024-06-12 15:32 UTC, kwoktung commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
如果需要配置 感觉也应该配置 network。

类似 service.getAllNetworks().filter(o => o.supportAddressBook).map(net =>network.id)

2024-06-12 15:32 UTC, originalix commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
是的，但是这部分又属于业务的特殊逻辑，最终是希望有一个地方能快速知道某些业务场景在网络选择器屏蔽了哪些链

2024-06-12 15:33 UTC, kwoktung commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
那可以统一写在一个地方好管理。我改改。

2024-06-13 02:50 UTC, kwoktung commented on packages/kit/src/views/AddressBook/components/CreateOrEditContent.tsx
> +];
统一写在 packages/kit/src/components/ChainSelectorInput/excludeNetworkIds.ts

2024-06-13 03:04 UTC, originalix approved these changes

2024-06-13 03:05 UTC, huhuanming approved these changes

2024-06-13 03:05 UTC, merged