feat: migration v4 discover data
OneKeyHQ/app-monorepo pull request #4765
Opened 2024-06-14 07:30 UTC by kwoktung

2024-06-14 08:26 UTC, originalix requested changes

2024-06-14 08:26 UTC, originalix commented on packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForDiscover.ts
> +    const rawData = await simpleDb.browserBookmarks.getRawData();
不要直接操作 v5 的数据库

2024-06-14 08:26 UTC, originalix commented on packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForDiscover.ts
> +    await simpleDb.browserBookmarks.setRawData({
这代码执行以后，v5 数据库原有的 rawData 不是都没了...

2024-06-17 03:11 UTC, kwoktung commented on packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForDiscover.ts
> +    const rawData = await simpleDb.browserBookmarks.getRawData();
看了一下 Bookmark 是用这个方法的。 serviceDiscover 保留单独的添加方法

```
  buildBookmarkData = contextAtomMethod(
    (_, set, payload: IBrowserBookmark[]) => {
      if (!Array.isArray(payload)) {
        throw new Error('buildBookmarkData: payload must be an array');
      }
      // set(browserBookmarkAtom(), payload);
      void backgroundApiProxy.simpleDb.browserBookmarks.setRawData({
        data: payload,
      });
    },
```
  );

2024-06-17 03:11 UTC, kwoktung commented on packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForDiscover.ts
> +    await simpleDb.browserBookmarks.setRawData({
已经修复

2024-06-17 05:04 UTC, originalix commented on packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForDiscover.ts
> +    const rawData = await simpleDb.browserBookmarks.getRawData();
这里的 get 也应该有相关方法，在方法里处理好 rawData 为空的场景

2024-06-17 13:03 UTC, kwoktung commented on packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForDiscover.ts
> +    const rawData = await simpleDb.browserBookmarks.getRawData();
改好了。

2024-06-17 13:24 UTC, originalix approved these changes

2024-06-17 13:33 UTC, weatherstar approved these changes

2024-06-17 13:41 UTC, merged