fix: fix OK-29400)
OneKeyHQ/app-monorepo pull request #4909
Opened 2024-06-24 18:01 UTC by huhuanming

2024-06-24 18:15 UTC, weatherstar approved these changes

2024-06-25 00:44 UTC, ByteZhang1024 approved these changes

2024-06-25 01:10 UTC, loatheb requested changes

2024-06-25 01:10 UTC, loatheb commented on packages/kit/src/views/Send/pages/SendDataInput/SendDataInputContainer.tsx
> +    void Promise.all([
这里为什么没有通用的方案，需要单独处理

2024-07-01 01:20 UTC, closed without merging