feat:remove keytag options in web platform  OK-29444 OK-29433
OneKeyHQ/app-monorepo pull request #4923
Opened 2024-06-25 08:05 UTC by kwoktung

2024-06-25 15:54 UTC, originalix requested changes

2024-06-25 15:54 UTC, originalix commented on packages/kit-bg/src/services/ServiceSignature.ts
> +    });
这里加一个合约交互的类型，并不能解决 signOnly 的问题啊

2024-06-25 15:55 UTC, originalix commented on packages/kit-bg/src/services/ServiceSignature.ts
> +    });
在 ServiceSend 的入口处已经过滤了 signOnly 的条件

2024-06-26 01:02 UTC, kwoktung commented on packages/kit-bg/src/services/ServiceSignature.ts
> +    });
改了。已经支持 添加 signOnly

2024-06-26 03:52 UTC, sidmorizon commented on packages/kit/src/views/KeyTag/pages/UserOptions/index.tsx
> +        {!platformEnv.isWeb ? (
platformEnv.isWebDappMode

2024-06-26 03:52 UTC, sidmorizon commented on packages/kit/src/views/KeyTag/pages/UserOptions/index.tsx
> +        {!platformEnv.isWeb ? (
同时在 serviceAccount.拦截一下 platformEnv.isWebDappMode 开启时，阻止创建 hd 钱包 createHDWallet 和私钥账户 addImportedAccount

2024-06-26 04:47 UTC, kwoktung commented on packages/kit/src/views/KeyTag/pages/UserOptions/index.tsx
> +        {!platformEnv.isWeb ? (
解决了

2024-06-26 05:52 UTC, originalix approved these changes

2024-06-26 05:59 UTC, huhuanming approved these changes

2024-06-26 05:59 UTC, merged