feat: filter out duplicate toasts by toastId
OneKeyHQ/app-monorepo pull request #5041
Opened 2024-07-03 10:29 UTC by huhuanming

2024-07-03 10:30 UTC, loatheb submitted a review, later dismissed

2024-07-03 10:32 UTC, originalix commented on packages/shared/src/errors/errors/baseErrors.ts
> +    this.toastId = toastId;
插件端应该不生效的 测了不

2024-07-03 10:42 UTC, huhuanming commented on packages/shared/src/errors/errors/baseErrors.ts
> +    this.toastId = toastId;
没问题的，验过

2024-07-03 10:44 UTC, huhuanming commented on packages/shared/src/errors/errors/baseErrors.ts
> +    this.toastId = toastId;
https://github.com/OneKeyHQ/app-monorepo/assets/5743863/07618a14-5432-4d38-9dd8-b321794fefde

2024-07-03 10:47 UTC, originalix approved these changes, later dismissed

2024-07-03 10:48 UTC, huhuanming commented on packages/shared/src/errors/errors/baseErrors.ts
> +    this.toastId = toastId;
有点问题。。

2024-07-03 10:50 UTC, originalix commented on packages/shared/src/errors/errors/baseErrors.ts
> +    this.toastId = toastId;
🐶

2024-07-03 10:55 UTC, originalix commented on packages/shared/src/errors/errors/baseErrors.ts
> +    this.toastId = toastId;
想给 error 加属性，得在 cross-in page-provider 的项目同步加，插件端在那序列化

参考我最近的一个 requestId 的 PR

2024-07-03 11:24 UTC, huhuanming commented on packages/shared/src/errors/errors/baseErrors.ts
> +    this.toastId = toastId;
奇怪，这个 toastId 在 error 传递的过程中丢失了。。。

2024-07-03 15:27 UTC, loatheb submitted a review, later dismissed

2024-07-03 15:31 UTC, originalix requested changes
Error 里不要增加 toastId 的属性了，改动有些重了

kit 层用 i18n 的 key 作为 toastId 或者映射一个 id

这样后续有需要消息去重的场景也可以通过 i18n 的 key 来作为唯一 id

2024-07-03 15:55 UTC, huhuanming commented
简化了

2024-07-04 02:22 UTC, originalix approved these changes

2024-07-04 04:03 UTC, loatheb approved these changes

2024-07-04 04:08 UTC, merged