chore: closing setting modal when currency/language is changed
OneKeyHQ/app-monorepo pull request #5126
Opened 2024-07-08 09:48 UTC by kwoktung

2024-07-08 14:36 UTC, weatherstar approved these changes, later dismissed

2024-07-08 15:13 UTC, huhuanming requested changes

2024-07-08 15:13 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceApp.ts
> +        global.location.href = '/';
不对，插件端  global.location.href 这拿到的是后台进程的 chrome-extension://{hash}/background.bundle.js

2024-07-09 01:21 UTC, kwoktung commented on packages/kit-bg/src/services/ServiceApp.ts
> +        global.location.href = '/';
改了。

2024-07-09 02:55 UTC, originalix submitted a review, later dismissed

2024-07-09 02:58 UTC, sidmorizon approved these changes, later dismissed

2024-07-09 03:05 UTC, huhuanming requested changes

2024-07-09 03:05 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
为啥要 clear 呢😂
html 的 theme 主题存放在 localStorage 里，clear 了，刷新后，启动时的背景色可能对不上哦。

2024-07-09 03:11 UTC, sidmorizon commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
因为有第三方库可能用到了 localStorage

2024-07-09 03:12 UTC, sidmorizon commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
RESET 之后，所有数据包括 theme 颜色也会重置，这里为什么会对不上，和用户重新安装一个 app 类似，所有数据都是空

2024-07-09 03:13 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
apps/ext/src/entry/content-script-init.ts 98L
apps/ext/src/assets/preload-html-head.js 35L

2024-07-09 03:16 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
但是这里只是 restartApp，不应该清除吧 😳

2024-07-09 03:22 UTC, huhuanming requested changes

2024-07-09 03:22 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
如果要清除应该写到 reset 里面去

2024-07-09 03:22 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
代码折叠了，是在 reset 里面。。

2024-07-09 03:22 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceSetting.ts
> +    await this.backgroundApi.serviceApp.restartApp();
这里重启会有风险吧

packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForSettings.ts 97L
迁移的时候设置语言，可能会导致 app 重启

2024-07-09 03:22 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceSetting.ts
> +    await this.backgroundApi.serviceApp.restartApp();
packages/kit-bg/src/migrations/v4ToV5Migration/V4MigrationForSettings.ts 76L
迁移的时候设置语可能会导致重启

2024-07-09 03:23 UTC, huhuanming commented on packages/kit-bg/src/services/ServiceApp.ts
>          global.localStorage.clear();
不好意思，看错了 😫

2024-07-09 05:48 UTC, huhuanming approved these changes

2024-07-09 05:49 UTC, originalix approved these changes

2024-07-09 06:03 UTC, merged