Feat: support scdo
OneKeyHQ/app-monorepo pull request #5278
Opened 2024-07-23 09:33 UTC by huanxiangspace

2024-07-23 15:17 UTC, originalix commented on packages/core/src/chains/scdo/CoreChainSoftware.ts
> +    };
scdo 不涉及软件端的 signTransaction 和 signMessage 方法吧

2024-07-24 00:50 UTC, huanxiangspace commented on packages/core/src/chains/scdo/CoreChainSoftware.ts
> +    };
这都是模版里的代码，没有用到，用不用删了？

2024-07-24 01:07 UTC, originalix commented on packages/core/src/chains/scdo/CoreChainSoftware.ts
> +    };
嗯，按需来，没用到的都用 `throw new NotImplemented();` 报错

2024-08-22 03:07 UTC, originalix requested changes

2024-08-22 03:07 UTC, originalix commented on packages/kit-bg/src/providers/ProviderApiScdo.ts
> +          accounts: { address: 'Your Account Address' },
获取 accounts

2024-08-22 03:07 UTC, originalix commented on packages/kit-bg/src/vaults/impls/scdo/KeyringHardware.ts
> +            };
接硬件 API，不要 mock

2024-08-22 03:07 UTC, originalix commented on packages/kit-bg/src/vaults/impls/scdo/KeyringHardware.ts
> +    // );
硬件 API

2024-08-22 03:07 UTC, originalix commented on packages/kit-bg/src/vaults/impls/scdo/KeyringHardware.ts
> +    // );
同上

2024-08-22 03:07 UTC, originalix commented on packages/shared/src/config/presetNetworks.ts
> +  scdo,
直接放到生产环境可见

2024-08-23 04:08 UTC, originalix approved these changes, later dismissed

2024-08-23 06:02 UTC, originalix submitted a review, later dismissed

2024-08-23 06:14 UTC, weatherstar submitted a review, later dismissed

2024-08-23 06:14 UTC, weatherstar commented on packages/kit-bg/src/vaults/impls/scdo/Vault.ts
> +        /^((1s01|2s02|3s03|4s04|1S01|2S02|3S03|4S04)[a-fA-F0-9]{37}[1-2])|0[sSx]0{40}|0x0[1-4][a-fA-F0-9]{37}[1-2]$/.test(
这个正则是怎么来的，最好有个规则注释或者测试用例，时间长了忘记了容易出问题

2024-08-23 06:21 UTC, huanxiangspace commented on packages/kit-bg/src/vaults/impls/scdo/Vault.ts
> +        /^((1s01|2s02|3s03|4s04|1S01|2S02|3S03|4S04)[a-fA-F0-9]{37}[1-2])|0[sSx]0{40}|0x0[1-4][a-fA-F0-9]{37}[1-2]$/.test(
这是从SCDO的源码里拿过来的

2024-08-23 06:42 UTC, originalix commented on packages/kit-bg/src/vaults/impls/scdo/Vault.ts
> +        /^((1s01|2s02|3s03|4s04|1S01|2S02|3S03|4S04)[a-fA-F0-9]{37}[1-2])|0[sSx]0{40}|0x0[1-4][a-fA-F0-9]{37}[1-2]$/.test(
从 Scdo 的 js-sdk 代码库里扒出来的

2024-08-23 06:43 UTC, originalix approved these changes

2024-08-23 08:57 UTC, weatherstar approved these changes

2024-08-23 09:03 UTC, merged