chore: v4 custom network/custom rpc url data
OneKeyHQ/app-monorepo pull request #5424
Opened 2024-08-05 11:12 UTC by kwoktung

2024-08-05 13:32 UTC, originalix requested changes

2024-08-05 13:32 UTC, originalix commented on packages/kit-bg/src/services/ServiceV4Migration/ServiceV4Migration.ts
> +        .filter((o) => networkUtils.isEvmNetwork({ networkId: o.networkId }));
自定义 RPC 全部导出，无需区分是否为 evm 网络

2024-08-05 13:32 UTC, originalix commented on packages/kit-bg/src/services/ServiceV4Migration/ServiceV4Migration.ts
> +    const v4localDb = v4dbHubs.v4localDb;
v4 的网络从 redux.runtime.networks 里取，这里是什么原因要从 db 取？还额外写了 realm 的 schema

2024-08-06 00:55 UTC, kwoktung commented on packages/kit-bg/src/services/ServiceV4Migration/ServiceV4Migration.ts
> +    const v4localDb = v4dbHubs.v4localDb;
redux.runtime 只有运行时才有数据。

2024-08-06 01:07 UTC, originalix commented on packages/kit-bg/src/services/ServiceV4Migration/ServiceV4Migration.ts
> +    const v4localDb = v4dbHubs.v4localDb;
明白了 👍

2024-08-06 08:57 UTC, kwoktung commented on packages/kit-bg/src/services/ServiceV4Migration/ServiceV4Migration.ts
> +        .filter((o) => networkUtils.isEvmNetwork({ networkId: o.networkId }));
改了

2024-08-06 09:32 UTC, loatheb approved these changes

2024-08-06 12:54 UTC, originalix approved these changes

2024-08-06 12:54 UTC, merged