Fix: scdo
OneKeyHQ/app-monorepo pull request #5636
Opened 2024-08-26 09:20 UTC by huanxiangspace

2024-08-26 09:30 UTC, originalix requested changes

2024-08-26 09:30 UTC, originalix commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +    if (softwareAccountDisabled && wallet?.type === WALLET_TYPE_HD && account) {
wallet?.type === WALLET_TYPE_HD 用 accountUtils.isHwAccount 替换

2024-08-26 09:30 UTC, originalix commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +      );
devices 数组会出现两句一样的 i18n 文案？

这里的 UI 有产品确定过么

2024-08-26 10:15 UTC, sidmorizon commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +            <Empty
空状态统一封装在 EmptyAccount.tsx 里，不要在这里写额外的分支逻辑

2024-08-26 11:15 UTC, huanxiangspace commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +      );
不会出现两句一样的 i18n 文案。UI产品看过

2024-08-26 11:20 UTC, huanxiangspace commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +            <Empty
这不是空账户，是不支持HD钱包显示一个提示文案，没法复用EmptyAccount

2024-08-26 12:12 UTC, originalix commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +            <Empty
可以抽成一个组件，把这里对文案的计算逻辑都放在新组件里

代表 softwareAccountDisabled 的场景

2024-08-26 12:12 UTC, originalix commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +            <Empty
不然都堆在首页这里会很乱

2024-08-27 02:06 UTC, huanxiangspace commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +            <Empty
@originalix 看看还需要调整不

2024-08-27 02:11 UTC, originalix commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +      }
这些计算逻辑也可以放入组件内，条件作为 props 传入

2024-08-27 02:24 UTC, huanxiangspace commented on packages/kit/src/views/Home/pages/HomePageView.tsx
> +      }
@originalix 再看看

2024-08-27 02:58 UTC, originalix approved these changes, later dismissed

2024-08-27 03:05 UTC, originalix commented
lint 修复一下

2024-08-27 06:06 UTC, originalix approved these changes

2024-08-27 06:38 UTC, weatherstar approved these changes

2024-08-27 07:03 UTC, merged