Fix: ton bugs (OK-31653, OK-31666, OK-31667)
OneKeyHQ/app-monorepo pull request #5638
Opened 2024-08-26 12:12 UTC by huanxiangspace

2024-08-26 12:16 UTC, originalix requested changes

2024-08-26 12:16 UTC, originalix commented on packages/core/src/chains/ton/CoreChainSoftware.ts
> +    }
看下其他钱包，导出没有 0x 前缀的，这里要统一一下，导出结果一致

2024-08-27 06:07 UTC, originalix approved these changes

2024-08-27 06:37 UTC, weatherstar approved these changes

2024-08-27 06:41 UTC, merged